### ISSUE TITLE
Maxed Shards

### ISSUE THREAD

**Issue by Eseria** [pokeclicker/pokeclicker#1446] opened 2021-07-04 19:54 UTC
**Current Behavior**
When you have all the shard levels maxed out, there is no point in getting shards anymore

**Improved Behavior**
There should be another use to shards other than just to increase attack

**Reason for change**
To give shards more purpose, especially in late game

**Detailed Description**
There are a few different ideas I've thought of, here are the easy ones

Shard shop like the battle shop except you can buy evolution items (use 10,000 grass shards to buy a leaf stone)
You can combine a certain amount to increase click damage (ex: 1,000 of each shard grants 1% increase in click damage)
You can "feed" pokemon, shards of their type to increase their base attack (ex: 100 shards for 1 point increase)
Replace the purchase of pokemon from shops using quest points to using shards instead (ex: buy eevee with 50,000 normal shards)

I've also thought of some other ideas, but these would be much more complex in creating

A pokemon "daycare lady" who will watch and auto breed 1 pokemon for you in exchange for shards of that type 
A customizable room for the player where they can purchase boosts in the form of decorations using shards
A play yard where you can gather your favorite pokemon and make poffin using shards and berries. The pokemon will then explore and maybe find items, quest points, dungeon points, money, berries, or really anything in the game but shards

There are a few more ideas I have too, but I don't want to word vomit them all. If you have any other questions or want more clarification message me on discord please Eseria#5131

PS: Thanks for making an awesome game =^.^=

**Comment by RedSparr0w** [comment] 2021-09-17 04:00
closing as duplicate of #672

Feel free to comment there if you have more info to be added.

**Closed by RedSparr0w** 2021-09-17 04:00 UTC
