### ISSUE TITLE
[SUGGESTION] More Poké Ball Selection Options for Quests, Ultrabeasts, etc.

### ISSUE THREAD

**Issue by JaredShiao** [pokeclicker/pokeclicker#3283] opened 2022-10-31 02:44 UTC
**Current Behavior**
Currently has 4 Options, for New Pokémon, New shiny Pokémon, already caught Pokémon, and already caught shiny Pokémon

**Improved Behavior**
An additional option for Pokémon who would fulfill a quest condition, whether it be typing, or a specific id, etc.

**Reason for change**
Overall, if you are trying to catch everything you run into, the more specific a quest, the more time is "wasted" by using pokéballs on others. This mean 
In addition to the feature that the pokéball selection hotkey not working outside of routes, it can be quite cumbersome (and may prevent some from clearing the dungeon at all) to have to go through the menuing frequently during dungeons if you're only trying to catch a specific Pokémon but don't want to deal with the pokéball animation for the rest of the wild encounters. 

**Detailed Description**
An updated or revised Pokéball Selection UI, with more options, the primary one being a category for Pokémon who would progress a quest. Other ideas could be Ultra Beast equivalent categories for captured and shiny statuses, also boss/rare status, for Pokémon like roamers and dungeon bosses, and maybe for Pokerus-affected Pokémon.

**Comment by RedSparr0w** [comment] 2022-10-31 03:30
Closing as duplicate of #1712

**Closed by RedSparr0w** 2022-10-31 03:30 UTC
