### ISSUE TITLE
Screen failed with hatchery and pokeball selector un android[Bug]: 

### ISSUE THREAD

**Issue by Ashlazar** [pokeclicker/pokeclicker#3929] opened 2023-02-09 21:21 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I use pokeclicker un my android device (Moto E40)
I have detectes two issues.

Te first one is in the hatchery when i put the Pokémons un delay. I detectes It when i reached jhoto anda you can put the first 4 Pokémons waiting to hatch. If i put only one It IS showed correctly, but when i put more they don't look normally that parte of the screen reacts in a strange way i Will put a photo to show It.
The other problem is when i try to choose the pokeball allí the screen sed in lines anda i must try to choose the ball without seeing anything.

### What did you expect to happen?

I expect that i could see allí the imagen in a perder way, not a screen with lines or supperposition of imagen.

### Steps to Reproduce

1. Go yo ball selector and open It
2. Balls aren't showed.

1.Reach jhoto región.
2. Put allí Pokémons un hatchery.
3. When you acumulate 2 of them on wait It fails showing the imagen.

### What operating system are you using?

Android

### What browsers are you seeing the problem on?

Chrome

### Additional Information

Pokemon hatchery bug
![Screenshot_20230209-221119](https://user-images.githubusercontent.com/124934727/217941729-3c6c34f1-22b3-44f0-a123-0105d25311dc.png)
Pokeball selector bug
![Screenshot_20230209-221127](https://user-images.githubusercontent.com/124934727/217941752-e8e29024-6261-40fe-9bcc-1aa690fae994.png)

**Comment by Aegyo** [comment] 2023-02-09 21:23
Is the browser up to date?

**Comment by DraKay** [comment] 2023-02-09 21:26
Never seen a bug like that... Do the phone enough memory to manage the game? (it should at it isn't too old)

**Comment by RegisCoaxans** [comment] 2023-02-09 22:15
I remember a bug report somewhat related but I can not find it anymore.
At that time, it was concluded that the bug was caused by the device being damaged and unable to render the game properly.
Either that is the reason or not, the bug is most likely due to your device anyway. Try first on another browser, then think about playing on another device as well.

**Comment by Ashlazar** [comment] 2023-02-10 07:24
I try to open the game in Brave browser and It works perfect. Maybe can be something in Chrome working in the device. I don't know; thanks for the help and i Hope i'm the only one with this problem.

**Comment by Aegyo** [comment] 2023-04-05 02:15
Closing as I don't think this is a problem we can fix, looks like a bug with that particular browser

**Closed by Aegyo** 2023-04-05 02:15 UTC
Labels: bug
