### ISSUE TITLE
[SUGGESTION]: Add the ability to import Vitamin Distribution using a txt doc

### ISSUE THREAD

**Issue by coolbond1** [pokeclicker/pokeclicker#4035] opened 2023-03-22 00:56 UTC
Current Behavior
Click on either + or - to add or remove vitamin in quantites of 1 5 10 or all.
Currently, while functional, it is incredibly slow if you need to redistribute all vitamins.

Improved Behavior
Able to import a txt to quickly set vitamins to what you want it to be.
For Example: "Venusaur 10 0 15" would set venusaurs protein to 10, remove all the calcium and set the carbos to 15.

Detailed Description
I understand there could be a LOT of issues with this but i think this is a necessary addition as even now we are up to almost 900 pokemons which means it will become more and more cumbersome to redistribute vitamins as the game goes on and a quick way to do this will be a necessity either with a button that automatically puts everything as optimal as possible or with an import option.

**Comment by Symi001** [comment] 2023-03-22 10:21
Looks like a duplicate of #4020

**Comment by Farboo171** [comment] 2023-05-03 22:54
is a duplicate of #4020 , closing

**Closed by Farboo171** 2023-05-03 22:54 UTC
