### ISSUE TITLE
[SUGGESTION] Hatchery Helpers should have an option that picks the next pokemon in the hatchery queue

### ISSUE THREAD

**Issue by trish-spaceexploreunit** [pokeclicker/pokeclicker#2106] opened 2022-04-30 13:05 UTC
**Current Behavior**
Currently, there's a lot of options for the Hatchery Helpers to hatch pokemon through. The default is ID. There is no option in the "Sort" for "queue" or similar. 

**Improved Behavior**
I would like to have the option for the Hatchery Helpers to pick the next available pokemon in the queue. 

**Reason for change**
When I place pokemon in the queue, I expect that they will be the ones that are hatched next. The fact that the helpers would hatch pokemon that _aren't_ in that queue actually surprised me. I can see the benefit - since they will continue to hatch even when the queue is empty. 

**Detailed Description**
I think a checkbox to say "Hatch what's next in the queue" would be helpful, and then after the queue is depleted, they choose based on the "Sort" selection. I think that this would circumvent potential issues where having it be an option in the "Sort" dropdown would prevent the helper from being able to keep hatching pokemon even with an empty queue. This would apply both for if the queue has run out naturally or for players still in Kanto without a hatching queue.

**Comment by amative1** [comment] 2022-04-30 19:13
The queue is your queue, not the Helper's queue. If you want them to grab the next best Pokémon, don't put it in your queue, leave it for theirs. Closing as this is a combination of "working as intended" and "duplicate suggestion per #2099 "

**Closed by amative1** 2022-04-30 19:13 UTC
