### ISSUE TITLE
[SUGGESTION] Independent Pokémon sorting for each view (hatchery, list, protein)

### ISSUE THREAD

**Issue by mouarflenoob** [pokeclicker/pokeclicker#1193] opened 2021-01-04 07:46 UTC
I'm on v 0.7.2 W10 Firefox 84.0.1

The sorting for the list of pokemon on the main page uses the same form as the sorting of pokemon in the Hatchery. Which makes that when I change the sorting of the pkmn list in theHatchery, it changes my sorting on the main page.
It's bothering me because I like to sort the eggs by Attack and the main list by level.

Both sorting should be independant.

**Comment by RedSparr0w** [comment] 2021-01-04 09:41
Not a bug, this is intended, have updated to be a suggestion.

**Comment by amative1** [comment] 2022-04-30 00:27
Fixed in #1645

**Closed by amative1** 2022-04-30 00:27 UTC
Labels: suggestion
