### ISSUE TITLE
[BUG] Some shops are not what they are supposed to be (default content)

### ISSUE THREAD

**Issue by Arkadynn** [pokeclicker/pokeclicker#2519] opened 2022-06-26 22:59 UTC
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version 0.9.6

**Description:**
when I access to some shops (ex : Poké mart Survival Area) there supposed content isn't available and I have 4 options Pokeball, Greatball, Ultraball, and "Item Name" (at a sold out price)

**Steps to Reproduce:**
1. Go to Survival Area in Sinnoh
2. Click on poké mart
3. See error

**Expected Behavior:**
Be able to buy Electrizer and Magmarizer

**Screenshots:**
<a href="https://imgur.com/z1CkUxi"><img src="https://i.imgur.com/z1CkUxi.png" title="source: imgur.com" /></a>

**Additional Information:**
This bug is not limited to this special shop, and happened to me randomly in any Poké Mart (including Masterball ones)

**Comment by PixLSteam** [comment] 2022-06-26 23:07
Duplicate of #2510, hopefully fixed by #2511

**Closed by PixLSteam** 2022-06-26 23:07 UTC
Labels: bug
