### ISSUE TITLE
[SUGGESTION] [DISCORD] Modification to the external scripts role

### ISSUE THREAD

**Issue by Bassem-Const** [pokeclicker/pokeclicker#2901] opened 2022-08-25 21:27 UTC
**Current Behavior**
Currently it doesn't matter how you use external scripts, whether it's just time skips, or giving yourself everything in the game, you get the same role if you get exposed.

**Improved Behavior**
Different roles for different levels of usage, lowest being recovery of lost progress (no role) 2nd being time skips (role similar to current role but temporary) 3rd being heavy usage (current role and permanent until the save is deleted)

**Reason for change**
Why would you punish someone who only used time-skips as much as someone who gave themselves everything with the same role, I think that time-skips have no sense in a ban from #bragging for that long, especially if you took a long break after that.

**Detailed Description**
Adding levels to external script usage to be a little fairer.

**Comment by PixLSteam** [comment] 2022-08-25 21:32
You're making this sound like a ranking system.

**Comment by Bassem-Const** [comment] 2022-08-25 22:15
> You're making this sound like a ranking system.

True

**Comment by space244-hub** [comment] 2022-08-25 23:27
Considering how low the skill ceiling is on the game any script that lowers time is a pretty big advantage since what you're really doing is trying to prevent yourself from getting so bored you quit. Not to mention how annoying it'd be to figure out just how much time you'd need to wait to cancel out the effect of any script you'd use.

**Comment by CorgiOnNeptune** [comment] 2022-08-26 00:01
The main point of external scripts role is to give devs/cc/mods an easy way to tell if somebody has altered savedata in any way which can have unintended consequences to a files data or gameplay. It saves time trying to help somebody with a bug that could have been caused by their own actions rather than an error in the normal code.

**Comment by jk13pclick** [comment] 2022-09-04 23:51
Closing this for several reasons, foremost of which is that suggestions for the Discord should go on the Discord repo. Additionally, while mods do not explicitly describe what it takes to earn the external scripts role, there is certainly some discretion involved in that decision. If you still feel strongly about this suggestion, please reopen it on the appropriate repo.

**Closed by jk13pclick** 2022-09-04 23:51 UTC
