### ISSUE TITLE
[Suggestion] Consolidated Shop Interface

### ISSUE THREAD

**Issue by danfroese** [pokeclicker/pokeclicker#664] opened 2020-04-17 20:27 UTC
It's nice unlocking new items to buy as you progress through the game, but having to hunt for the location of the item you want to buy can get old. I suggest a consolidated shop interface where all items that are available for purchase anywhere you have access to can be purchased. (Pokemon Black/White did something like this with the shops in the Pokemon Centres which had better inventories as you unlocked Gym Badges.)

**Comment by Popoteguitou** [comment] 2020-04-18 08:01
duplicate of another issue i think

**Closed** 2020-09-05 04:55 UTC
