### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by THRILLHO727** [pokeclicker/pokeclicker#2522] opened 2022-06-27 10:46 UTC
**Info**
 - OS: [Android Phone]
 - Browser [Chrome]
 - Version [`v0.9.6`]

**Description:**
cannot use  token collector item from battle item menu.  All other items work fine

**Expected Behavior:**
token collector bonus would be applied when I tapped the item

**Screenshots:**
[Screenshot_20220627-064605_Chrome](https://user-images.githubusercontent.com/108271401/175924400-959950ef-f52f-4d31-82cc-8033dc1e32df.jpg)
 -->

**Additional Information:**

**Comment by Qwertypop04** [comment] 2022-06-27 10:49
Closing as duplicate of #2520

**Closed by Qwertypop04** 2022-06-27 10:49 UTC
Labels: bug
