### ISSUE TITLE
[SUGGESTION] Getting rid of access battle items

### ISSUE THREAD

**Issue by elestria1** [pokeclicker/pokeclicker#1617] opened 2021-10-03 16:51 UTC
**Current Behavior**
 For right now, extra battle items (picked up in dungeons) sometimes lay dormant in inventory, sometimes forever.

**Improved Behavior**
 It would be nice to have the option of deletion or to sell them back at reduced prices.

**Reason for change**
 For some people (especially those who are currently running the no battle item challenge mode) battle items are not used. I for one usually end up picking up said items when running tough dungeons. If one has enough of them, I think it might lead to a bit of a nuisance or maybe lag. 

**Detailed Description**
 I would suggest that maybe next to the option of (x1, x10, x100, x1000, and all) you should have a garbage option to delete extra items. Or maybe add a sell feature to the store.

**Screenshots:**

**Comment by jk13pclick** [comment] 2022-06-06 03:53
Duplicate of #2343, closing.

**Closed by jk13pclick** 2022-06-06 03:53 UTC
