### ISSUE TITLE
[BUG] Underground energy overflow

### ISSUE THREAD

**Issue by Javier9989** [pokeclicker/pokeclicker#2763] opened 2022-07-26 18:41 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
Underground energy was over the max Value or not lowering

**Steps to Reproduce:**
1. Go to Underground
2. See error on infinite loop
3. Holding Rocky Helmet, Explosive Charge and Treasure Scanner.
4. Accidentally, pressing numpad 1 key

**Expected Behavior:**
Do not show the message spaming like hell and, to my regret, cap the underground energy to its correct value

**Comment by PixLSteam** [comment] 2022-07-27 16:17
Do you have any screenshots you can provide?

**Comment by Javier9989** [comment] 2022-07-28 06:06
![Captura](https://user-images.githubusercontent.com/110058165/181432419-6b09e06d-0ea2-4028-a862-98a4ce0ab319.PNG)

Confirmed it happens when numpad 1 key is pressed

**Comment by Javier9989** [comment] 2022-07-28 06:07
I know it's trying to use a potion but i could use hammer several times without losing energy nor potions.

**Comment by Jaaslet** [comment] 2022-08-06 16:13
The spam is just standard behavior. If you hold down a button, it's the same as pressing it quickly.
And i can't reproduce the overflow thing... Do you have any more details?

**Comment by Aegyo** [comment] 2023-04-10 01:19
Closing as unable to reproduce

**Closed by Aegyo** 2023-04-10 01:19 UTC
Labels: bug
