### ISSUE TITLE
[SUGGESTION] Add custom Pokemon capture filter option

### ISSUE THREAD

**Issue by Pacdac** [pokeclicker/pokeclicker#2240] opened 2022-05-25 08:41 UTC
**Current Behavior**

We can choose pokeball type for 4 types of encounters: Caught, caught shiny, new, shiny

**Improved Behavior**

Possibility to set a custom filter for the Pokemons we want to caught, and choosing which pokeball we want to use for this filter.
Examples : 
- Capturing only already captured Grass type pokemons
- Capturing only a certain legendary Pokemon with a MasterBall

**Reason for change**

It would allow players to diminish lost time and pokeballs for quests requiring to capture an exact type of pokemon and give them more liberty on what to capture.

**Detailed Description**

The filter would be something similar to the one in the Pokedex or DayCare menu.
The option to create a capture filter could be unlocked in later regions, and/or more custom filters slots could be unlocked throughout the game. 
If implemented, being able to filter on legendary Pokemons could allow players to use MasterBalls in an easier way.

**Screenshots:**

**Comment by Jaaslet** [comment] 2022-05-25 08:45
Closing as a duplicate of #2046.
If you have more filters you want, add a comment to that issue

**Closed by Jaaslet** 2022-05-25 08:45 UTC
