### ISSUE TITLE
Qwertypop

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#2457] opened 2022-06-15 14:58 UTC
Pls dock shortcut.
How get blu?
My achievements are bugged and my farmhands keep quitting.
Distortion world bugged. Can't find.

**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

Riolu bugged.
Volcarona bugged.
Volcanion bugged.
Make game easier. Too hard.
How go next region?

PLS

**Comment by PixLSteam** [comment] 2022-06-15 14:59
![image](https://user-images.githubusercontent.com/21047644/173859751-b9b405a9-e4bb-4c06-a54f-737c70c125d2.png)

**Comment by Qwertypop04** [comment] 2022-06-15 15:08
1. No dock shortcut
2. Gain Dungeon Tokens by catching Pokemon
3. Achievement and Farmhand bug will be fixed in the next update
4. Riolu can only be evolved at daytime, between 6am and 6pm
5. You can get the pre-evolution of Volcarona by breeding it.
6. You can unlock Volcanion by defeating the dungeon 5 times and defeating Champion Diantha
7. No.
8. Go to the next region by completing the Pokedex and going to the starting town
9. Ultima isn't funny

**Closed as not planned** 2022-06-15 15:08 UTC

**Comment by Ultima1990** [comment] 2022-06-15 16:20
2. But how can I catch? I already catcheded all! Bug!
4. Is daytime now. Can't see evolve button. Bug!
5. But Volcarona locked. Can't see how to unlock. Bug!
8. I don't see any uncatchededed in the pokemondex, but professor says I need 1 more. Bug!
9. Rude. Bug!

**Comment by Qwertypop04** [comment] 2022-06-15 16:38
2. Set the icon under caught to pokeball to recatch Pokémon.
3. In game day and night is based on your computer's time, If you cannot evolve riolu, it is not currently between 6am and 6pm.
4. My mistake, Volcarona is locked because you have not cleared Relic Passage. It is the dungeon in the water near Relic Castle. If you are struggling to see it, change your colour highlights to a more visible colour.
5. Pokedex only shows up to the last Pokémon seen, you have not seen the last Pokémon in your current regions pokedex yet.
6. Yes, rude. Not a bug.
