### ISSUE TITLE
[BUG] Locked routes since last update

### ISSUE THREAD

**Issue by Narcisse-666** [pokeclicker/pokeclicker#2735] opened 2022-07-23 12:11 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.9.9

**Description:**
Since last update, routes 218 and 219 in Sinnoh are inaccessible saying I need to beat "Galaxy Boss Cyrus" to unlock them. I have beaten Sinnoh a long time ago and I tried beating Cyrus in Distortion world and Team Galactic HQ again. These two routes are still locked away.

**Steps to Reproduce:**
I guess go back to previous version, go up to Unova then update to v0.9.9...?

**Expected Behavior:**
Unlocking the routes when beating Cyrus again

**Screenshots:**
![Capture2](https://user-images.githubusercontent.com/109857198/180604366-c65257ba-2ed7-49ba-a9c7-a35b3d41f335.png)

**Comment by Qwertypop04** [comment] 2022-07-23 12:16
You haven't beat the new Cyrus temporary battle in Celestic Town. Not a bug.

**Comment by Narcisse-666** [comment] 2022-07-23 12:19
Well I would have done it if I had access to it
![Capture](https://user-images.githubusercontent.com/109857198/180604568-ef504ca1-8d24-430d-85db-088013cc6eb6.PNG)

**Comment by Ultima1990** [comment] 2022-07-23 12:28
Please attach a copy of your save.

**Comment by Narcisse-666** [comment] 2022-07-23 12:28
[[v0.9.9] PokeClickerSave_2022-07-23 12_28_27.txt](https://github.com/pokeclicker/pokeclicker/files/9173754/v0.9.9.PokeClickerSave_2022-07-23.12_28_27.txt)

There you go

**Comment by Ultima1990** [comment] 2022-07-25 10:23
Fixed by #2740 and #2749.

Some saves progressed through Sinnoh at a time when questlines were failing to initialize. Not your fault, just bad timing.
The upcoming 0.9.10 should start the Galactic questline for all saves where this is the case. Progressing through the questline will lead you to the temporarybattle that is blocking these routes.

**Closed by Ultima1990** 2022-07-25 10:23 UTC
Labels: bug
