### ISSUE TITLE
[SUGGESTION]: Make an auto-completion / auto-restart for dungeons

### ISSUE THREAD

**Issue by Tr4hern** [pokeclicker/pokeclicker#3470] opened 2022-11-24 22:30 UTC
### Current Behavior

You have to do it by hand 500 times to get the final achievement of each dungeons

### Improved Behavior

A mean to automatically complete dungeons similar to the gyms auto-restart

### Reason for change

Make it easier to get the dungeon clears achievements

### Detailed Description

The auto-completion / auto-restart could be coming with the 250 clear success, in comparaison to the 100 clear gym success giving the auto-restart (this success is after obtaining flash so players doing these achievements will know this functionallity exists)
A way to do it could be to clear column by column and just do the bosses when on it (i don't think there will be dungeon with the ladder with 250 clears done), with this, it will be easier to get the achievement but the players will have to do it themselves to get chests). To simplify the coding and keep the completion kinda random, it could not take into account the information given by flash and just go up and down or right and left until finding the boss

**Comment by PixLSteam** [comment] 2022-11-24 22:34
Duplicate of #1315

**Closed by PixLSteam** 2022-11-24 22:34 UTC
Labels: suggestion
