### ISSUE TITLE
[Bug]: Safari Zone map size limited by window size

### ISSUE THREAD

**Issue by umbralOptimatum** [pokeclicker/pokeclicker#4616] opened 2023-08-03 21:34 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When the Safari Zone generates its map, the map size is limited by the current size of its modal. This creates unintuitive behaviors with very small windows. Expanding the window to full size does not change the map's height, leaving it comically small, but fills space horizontally with inaccessible ground tiles. This can also happen when the window is max size but the modal has less room for other reasons, like having the console open (how I discovered this while testing a different PR).

### What did you expect to happen?

The Safari Zone should generate maps with a fixed size. If the window is too small to display the full map, it should scroll to center the player like in the sprite-based pokemon games. The current behavior is unintuitive and very confusing for something trying to closely replicate the original Safari Zone experience.

As encounters or items could generate offscreen this way, this would require some way to tell where they are. Easiest to implement would be making the map a regular scrollable element so the player could look at any part of the map, recentering on the player upon movement. A more complicated but probably more user-friendly method would be locking scrolling and displaying the offscreen pokemon/item's icon in a bubble at the edge of the screen pointing to its offscreen position.  

I know #4590 already fixed the map generating with zero size, but it's still annoying to accidentally generate an atypically-small map and only be able to reset it by playing through the whole thing or restarting the game. This might also be a balance issue—I'm pretty sure pokemon/item spawn chance is independent of map size, so it's technically optimal to play on the minimum size map to reduce time spent on movement between encounters.

### Steps to Reproduce

1. Reduce window size so that the modal shrinks
2. Enter Safari Zone
3. Map remains at current size even if window expands

### What browsers are you seeing the problem on?

Firefox, Desktop Client

### Additional Information

Map generated in a small window:

<img width="770" alt="Screen Shot 2023-08-03 at 3 47 38 PM" src="https://github.com/pokeclicker/pokeclicker/assets/12092270/7556e069-5928-40a0-b370-4e759e60483f">

The same map after maximizing the window, with unchanged vertical size and all tiles right of the player sprite fake and inaccessible:

<img width="1440" alt="Screen Shot 2023-08-03 at 3 48 12 PM" src="https://github.com/pokeclicker/pokeclicker/assets/12092270/83f198f9-e273-4a5f-bc70-8e835891a8e0">

**Comment by CypherX** [comment] 2023-08-03 21:36
Leave tiny safari alone!

**Comment by Qwertypop04** [comment] 2023-08-03 21:39
Closing as not a bug. Make a suggestion if you wish this to change.

**Closed by Qwertypop04** 2023-08-03 21:39 UTC
Labels: bug
