### ISSUE TITLE
[SUGGESTION] New Shortcut for Eggs / Evolution Items

### ISSUE THREAD

**Issue by volchh** [pokeclicker/pokeclicker#2413] opened 2022-06-09 18:14 UTC
**Current Behavior**
The player must search each town in a new location to find evolution items and eggs of different types.

**Improved Behavior**
Add a tab similar to the Poke Mart shortcut that allows the player to more conveniently access eggs and other items in one place.

**Reason for change**
It can be difficult and time-consuming to try and search through every town in ever map to identify which Poke Mart has the items the player is searching for.

**Detailed Description**
If the current design is in place to keep players from using a new area's evolution items or egg types too early, add them to the Poke Mart shortcut once they would be unlocked through normal gameplay means. Previously unlocked items (such as egg types that don't change much from region to region) could become available in a new region once more after reaching that region's dock, and the player is at the point where they could travel backwards to previous regions to search for eggs / items.

**Screenshots:**
![2MtoFTi](https://user-images.githubusercontent.com/43535807/172916233-af91bb69-f0c8-40c2-9223-0ffea759781a.png)

**Comment by Ultima1990** [comment] 2022-06-10 14:55
Why don't you want to explore the map? Get immersed in this Pokémon world that you like because you are playing a Pokémon _fan game_. Have a look around, visit some towns. You'll find the stone in every region after it's first introduced.

(except don't go looking for a Moon stone in Johto, I recently discovered that we forgot to add it there...)

**Comment by jk13pclick** [comment] 2022-06-10 17:35
More or less a duplicate of #1714

**Comment by volchh** [comment] 2022-06-10 17:59
It's not like I don't want to explore and play the game, or anything like that. 

It would just be a nice quality of life addition (similar to the existing shortcuts). My current issue is really just that it can be cumbersome searching through each individual town to locate where the one specific egg type I need is, and then my own poor memory making me do the search all over again next time I need to find more of that egg. 

In my mind, the reasoning is similar to NiCeDiCe90's explanation of the introduction for shortcuts- I could write down a little document to help myself keep track of what regions have what eggs / evolution items in what towns and travel back to them each time, but I think it would make gameplay feel smoother if there was a more convenient / central location to find them!

Adding them to the Poke Mart shortcut would be very nice too, it doesn't have to be its own thing!

**Comment by jk13pclick** [comment] 2022-06-10 18:03
1. That document with all the shops exists - it is the wiki 😉 
2. I'm opposed to giving away free stuff. It's lame. So if we want to do this I propose making items found in centralized shops cost more than their shop counterparts. And we should also make these Shortcuts purchasable, not unlocked automatically with standard progression.

**Comment by Jaaslet** [comment] 2022-06-13 11:49
I will close this issue. We want to move towards having the map as the main interface, not away from it

**Closed** 2022-06-13 11:55 UTC
