### ISSUE TITLE
[BUG] Safari zone modal is dismissable which soft locks the safari zone

### ISSUE THREAD

**Issue by asg86260** [pokeclicker/pokeclicker#756] opened 2020-09-22 04:39 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Description:**
clicking outside of the safari zone modal will dismiss it, and when you click the safari zone modal back up your character can't move or click the leave button. 

**Steps to Reproduce:**
1. Be in safari zone
2. click outside the modal to dismiss it
3. click back into the safari zone on the map
4. character can't move and leave button doesn't work.

**Expected Behavior:**
either you cant dismiss the modal, or you get a warning saying you wont be allowed back in.

**Comment by Makeshift** [comment] 2020-09-22 16:34
Additionally, clicking on the 'help' tab while in the Safari Zone will cause it to softlock.

**Comment by RedSparr0w** [comment] 2020-09-23 00:17
Can't reproduce this myself, are any other devs able to?

Working fine for me:
![Safari](https://user-images.githubusercontent.com/7288322/93949922-12c45580-fd96-11ea-96a0-05fd79ddd9ed.gif)

**Comment by LuqDragon** [comment] 2020-09-24 02:54
just happened to me once, I will try with a new save in another browser

**Comment by LuqDragon** [comment] 2020-09-24 03:12
I got it, just start a new save, enter in safari, start a battle and click out of modal. 
The pad disappears and the character stuck, cant enter in help tab too.
I can click out of safari and its close. 
Enter again and it still stuck. 
Nothing in console

**Comment by RedSparr0w** [comment] 2020-09-24 03:22
What browser and version?

I can't get the modal to close by clicking outside of it or pressing escape.

**Comment by LuqDragon** [comment] 2020-09-24 03:29
Browser: Opera (i don't know the version, I will edit if I found)

it's not about the browser, when you start a new save, maybe this mechanism is off, you can click out modal, after refresh, it apply, that's the problem

**Comment by LuqDragon** [comment] 2020-09-24 03:42
[[v0.5.3] PokeClickerSave_2020-09-24 03_40_48.txt](https://github.com/pokeclicker/pokeclicker/files/5273297/v0.5.3.PokeClickerSave_2020-09-24.03_40_48.txt)
With that save we can reproduce it

**Comment by LuqDragon** [comment] 2020-09-24 06:14
the issue is fixed adding `data-backdrop="static" data-keyboard="false"` to the modals of safari, equals the modal when you get a badge, but I don't know why this happens with a new file and disappear when refresh after unlocking safari

**Comment by RedSparr0w** [comment] 2020-09-24 06:30
Hmm, that's strange because we already set backdrop static and keyboard false when displaying the modal 🤔 
But no harm adding it to the HTML as well.

https://github.com/pokeclicker/pokeclicker/blob/85975e9ad7d3a5cf3d27d8b24bc7cca9d7385485/src/scripts/safari/Safari.ts#L126

**Comment by LuqDragon** [comment] 2020-09-24 06:32
I tried open with `Safari.openModal()` and not work too

**Comment by RedSparr0w** [comment] 2020-10-03 04:34
Going to close this as fixed by PR #774 
If we encounter it again, please comment/re-open

**Closed by RedSparr0w** 2020-10-03 04:34 UTC
Labels: bug
