### ISSUE TITLE
[SUGGESTION]: Add an option to sell vitamins.

### ISSUE THREAD

**Issue by UnicornSnuggler** [pokeclicker/pokeclicker#3845] opened 2023-01-23 15:29 UTC
### Current Behavior

Presently, there is no way to sell any unused vitamins. No matter how many vitamins a user has bought throughout their PokéClicker "career," they will be stuck with them until the end of time.

### Improved Behavior

Users should be allowed to sell back unused vitamins for a substantially discounted price. Even if the rate of return is drastically low — something in the realm of 5% or 10% of the purchase price — users could still recuperate some of the cost of the vitamins they are no longer using.

### Reason for Change

There is merit to using Protein in earlier regions when the vitamin cap per-Pokémon is very low. Accordingly, it makes sense that the average user would buy plenty of Protein in the early game and max out their Pokémon with it to get the most out of their hatchery steps, especially considering how affordable it is in comparison to the monetary rewards for trainer battles in the earlier regions. As users advance through the regions and the vitamin cap per-Pokémon increases, however, Calcium and Carbos become much more relevant. Thus, it makes sense that the average user would then gradually retract their Protein toward the late game, favoring a healthy balance of Calcium and Carbos. This results in a phenomenon in which users possess an overabundance of Protein that are then no longer used in the late game.

Allowing the user to sell their unused vitamins — even for a _deep_ discount — would prevent them from feeling like their money was wasted in the early game — or, less importantly, from being displeased by the aesthetic dissonance of the enhanced vitamins screen showing several thousand unused vitamins.

### Detailed Description

The following table outlines the number of Protein a user would need for maximum efficiency on every Pokémon for each region, accounting for debuffs. This assumes that the user is playing 100% optimally and shifting their vitamins around as soon as they reach a new region _and_ that the user possesses all Pokémon in the active region as well as all of the forms _(which isn't entirely realistic, but it's the best that could be done for the sake of discussion)_.

![image](https://user-images.githubusercontent.com/10764837/214104951-8094ccfc-1db9-4701-8dde-3a17e539fc71.png)

I can't speak for everyone, but I know that I personally would not have been playing 100% optimally if I'd been running through the game for my very first time post-vitamins update. I also know that I'm not even playing 100% optimally at this very moment. Despite only being 4 Pokémon away from completing the Galar Pokédex, I am still missing a few hundred various forms of Pokémon in the game _(and I imagine the same is true for most people who are this late in the game)_. I also know that most people, like myself, hatch by descending breeding efficiency, which means they are more likely to start pumping vitamins into the most efficient Pokémon — which, unsurprisingly, requires more Calcium and Carbos than Protein due to the higher base attack values of those Pokémon.

By the time a user gets to the late game, the fact that Protein increases the step requirement of a Pokémon means that most people won't put a single Protein on a Pokémon unless they have a Carbos to balance it out for fear of losing efficiency. So the chances are incredibly good that until a user can afford an abundance of Carbos — which the table above demonstrates a substantial need for — they will force their Protein to sit in a pile off to the side until they can counteract the step requirement increase and instead focus on breeding only the Pokémon that they can funnel Carbos into.

### Another Perspective

In addition to the scenario above, there's another factor to consider. Prior to one of the latest updates that introduced Calcium and Carbos, the only available vitamin for raising the step attack bonus for a Pokémon was Protein. As such, it made a lot of sense to buy as much Protein as possible and max out all of your Pokémon with it — even in the late game. Then, the update dropped and vitamins got a rework, which meant that maxing Protein was no longer the most viable option for all Pokémon and a lot of users retracted a lot _(if not all)_ of their Protein to replace them with a healthy balance of Carbos and/or Calcium. This left most pre-vitamins update users with thousands of Protein just sitting there, never to be attached to a Pokémon again. The proposed solution helps alleviate that dilemma.

Finally, there is the case of fat-fingering or mis-clicking. If the user accidentally buys the wrong kind of vitamin in bulk _(or in the wrong quantity)_, there is no way for them to "undo" their mistake and they must simply live with it, mourning their lost money. The proposed solution would help mitigate some of those woes as well.

**Comment by CypherX** [comment] 2023-01-23 15:32
Partial duplicate of #3718

**Comment by Aegyo** [comment] 2023-01-23 15:34
I'll close the other one instead since this has more detail.

**Comment by UnicornSnuggler** [comment] 2023-01-23 15:34
Oh, crap. You folks are absolutely correct. I should have checked beforehand. Hopefully my expanded rationale helps substantiate things, though!

**Comment by Aegyo** [comment] 2023-01-23 15:40
Could you add numbers for how exactly how many proteins are needed to max vitamins before carbos/calcium is unlocked, and how many are optimal in galar? Also if possible, how many will be optimal in gen 9?

**Comment by UnicornSnuggler** [comment] 2023-01-23 16:20
I have added a table and a much deeper statistical analysis within the **Detailed Description** section.

**Comment by DraKay** [comment] 2023-01-23 16:28
Looking at the table proteins maybe can arrive the pick in Gen 9, but calcium won't... More than half of the sinnoh calcium is leftover in galar... Curious, the real problem isn't protein but calcium...

**Comment by Aegyo** [comment] 2023-01-23 16:31
I don't understand the part about people taking out a bunch of protein because they don't have carbos to offset the step increase - why would they not leave the protein on the pokemon until they have carbos to replace it with?

**Comment by UnicornSnuggler** [comment] 2023-01-23 16:41
I can't speak for everyone, but I'll give you my take on the subject.

As of this moment, assuming you're in Galar and have every Pokémon and every form in the game, if you sort them all by their breeding efficiency at max vitamins, the first one on the list you encounter _(at spot number 164)_ is Totem Togedemaru. Its breeding efficiency at 13 Protein and 27 Carbos is `2.23`. With just the 13 Protein, that breeding efficiency plummets down to `2.06`. Without any Protein at all, it sits at `2.10`. So it's actually better for it not to have any Protein if you don't have the Carbos to offset the step requirement increase.

![image](https://user-images.githubusercontent.com/10764837/214095301-89b0a242-6abe-4df2-850d-2507424ee070.png)

Granted, that's the _most_ efficient Pokémon with a Protein requirement. Spinda, for example, wants 17 Protein and the `1.45` efficiency you get with just the Protein and none of the Carbos is better than its base `1.13` without any vitamins at all. But Spinda is also at spot number 547 on the descending breeding efficiency list, so it's hardly ever in my hatchery.

That said, I see your point that I could be throwing my Protein onto all of the Spinda-type Pokémon who want it _and_ whose efficiency goes up even without the Carbos. So in that sense, it wouldn't be sitting in a pile being wasted. So really it boils down to a per-Pokémon basis.

**Comment by Aegyo** [comment] 2023-01-23 16:42
Your table also looks as if it is counting proteins for all pokemon, instead of just the pokemon possible to obtain by that region

**Comment by UnicornSnuggler** [comment] 2023-01-23 16:45
You are correct regarding that assertion. It's assuming you have every Pokémon and form in the game, whether they belong to that region or not — and it's taking into account the regional debuff associated with that region. Like I said, it's representing _maximized optimal play_, which isn't entirely realistic.

I could probably throw together another table representing the vitamin requirements for the Pokémon from each region _(at Galar and accounting for the Galar debuff)_ if you'd like?

**Comment by UnicornSnuggler** [comment] 2023-01-23 17:17
Oof. You are absolutely correct. I thought the cells weren't summing hidden rows, but they most certainly were. I have created a new _(more accurate)_ table, edited it into the post, and removed the misguided sentiments regarding it. It's clear now the Protein situation is less dire, but DraKay's sentiments about Calcium still stand.

**Comment by Aegyo** [comment] 2023-01-23 17:22
The leftover calcium looks like they will be used up in gen 9, so in my opinion it isn't much of a problem.

The situation with old players left on a pile of unusable proteins is still there, but I don't think we should add a sell option to the game just for that. Maybe a one time option on update to refund all unused proteins instead.

**Comment by UnicornSnuggler** [comment] 2023-01-23 17:34
This is only tangentially-related to the discussion at hand, but while I was making spreadsheets and had all this data collected, I went ahead and threw this together.

![image](https://user-images.githubusercontent.com/10764837/214109147-23d6a6ac-2ebe-49d1-9316-2dba42ed37e8.png)

**Comment by Aegyo** [comment] 2023-01-23 17:35
I'm sure some people would be interested in a link to your spreadsheet as well, if you want to share it

**Comment by DraKay** [comment] 2023-01-23 17:36
This cost are a bit misleading because you are adding previous regions on them. As I can see galar sum is whole sum

**Comment by UnicornSnuggler** [comment] 2023-01-23 17:49
What I was going for was, "How much money will I have spent to max out vitamins by the end of this region?" But I went ahead and added another column.

![image](https://user-images.githubusercontent.com/10764837/214111011-4260d899-2b97-4357-92bf-b0fd78c71c31.png)

I also published this to its own spreadsheet, which can be found [here](https://docs.google.com/spreadsheets/d/1bw_9TQO50BAi4Uu6iGE6ui96oidsaUr5SUGASFZ-D6k). If you folks want me to modify this with any new information _(such as Generation 9 when it's released)_, just let me know! You can also contact me on Discord; my handle is `Unicorn#2366` _(and I'm pretty active on the PokéClicker Discord server)_.

**Comment by DraKay** [comment] 2023-01-23 17:54
As I imagined unova is very heavy in money needed

**Closed** 2023-01-24 08:09 UTC
Labels: suggestion
