### ISSUE TITLE
[Bug]: Incorrect Johto Elite 4 Background

### ISSUE THREAD

**Issue by NAFEDUDE** [pokeclicker/pokeclicker#4571] opened 2023-07-23 01:11 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

All the Johto Elite 4 use the standard field background during their fight instead of backgrounds that fit their type/

### What did you expect to happen?

The backgrounds to match the members' types.

### Steps to Reproduce

1. Go to Johto Indigo Plateau
2. Fight Will, Koga, Bruno, Karen, or Lance

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Desktop Client

**Comment by osherwott** [comment] 2023-07-23 01:17
This is being worked on (we don't have a background for dark types yet)
Closing, as duplicate of #2156 
Thank you for the submission nevertheless! 👍

**Closed by osherwott** 2023-07-23 01:17 UTC
Labels: bug

**Comment by NAFEDUDE** [comment] 2023-07-23 05:09
Oh, jeez, sorry; I looked around just to make extra sure it wasn't already reported but I guess I just didn't find the right keywords.
