### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dastarox** [pokeclicker/pokeclicker#2562] opened 2022-07-02 08:26 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
Impossible d'activer le bonus de donjon token

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by Qwertypop04** [comment] 2022-07-02 08:33
Duplicate of https://github.com/pokeclicker/pokeclicker/issues/2551 https://github.com/pokeclicker/pokeclicker/issues/2522 https://github.com/pokeclicker/pokeclicker/issues/2520 https://github.com/pokeclicker/pokeclicker/issues/25258 https://github.com/pokeclicker/pokeclicker/issues/2561
Should be fixed with https://github.com/pokeclicker/pokeclicker/pull/2543

**Closed by Qwertypop04** 2022-07-02 08:33 UTC
Labels: bug
