### ISSUE TITLE
[SUGGESTION]: Hotkey for battle items (like xAttack and xClick)

### ISSUE THREAD

**Issue by LMorn** [pokeclicker/pokeclicker#4596] opened 2023-07-29 01:35 UTC
### Current Behavior

There is no hotkey for battle items

### Improved Behavior

A hotkey such as B + [1-6] to quickly use your already selected amount of a battle items, such as B + 1 to use xAttack and B + 2 to use xClick
Personally I would just set 1 through 6 to be battle items buttons not the PokeBall selection, but that would be confusing so I instead suggest a button like B or shift or ctrl

### Reason for change

Ease of use, and less clicking downtime or fine movement of mouse

### Detailed Description

There are hotkeys for a variety of things, like opening your pokeball filters or opening an Elite Four battle, but currently you have to waste time clicking on battle items when you could be clicking on the enemy pokemon. Also it would just be a lot less hassle, even if you don't click your enemies, because it would let you start a dungeon and your items at the same time rather than having it time out too soon or start too late. Especially good for people who have trouble moving their mouse with much accuracy, since even a normal person is gonna require at least some small time finding the exact point to place their mouse and not click the wrong item

**Comment by Farboo171** [comment] 2023-07-29 01:43
Duplicate of #1578, closing

**Closed by Farboo171** 2023-07-29 01:43 UTC
Labels: suggestion
