### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sithlordkennus** [pokeclicker/pokeclicker#2558] opened 2022-07-01 12:31 UTC
**Info**
 - OS: google android os
 - Browser Chrome
 - Version 

**Description:**
Can not tap token collector at all. Every other battle item works.

**Steps to Reproduce:**
Always

**Expected Behavior:**
Tap to use token collector in battle items

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment] 2022-07-01 12:34
Duplicate of #2551 #2522 #2520 
Hopefully fixed with #2543

**Closed by PixLSteam** 2022-07-01 12:34 UTC
Labels: bug
