### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Aimek96** [pokeclicker/pokeclicker#1628] opened 2021-10-28 16:29 UTC
Prestige Mode

**Current Behavior**

**Improved Behavior**
I would like a prestige mode of sorts

**Reason for change**
Would add extra hours of replay value
**Detailed Description**
This game is perfect but it would be cool to prestige once you reach the end and then get a boost to catch rate or maybe can unlock special pokemon or maybe a boost to shiny rate

**Screenshots:**

**Comment by RedSparr0w** [comment] 2021-11-06 04:38
Closing as duplicate of #238

**Closed by RedSparr0w** 2021-11-06 04:38 UTC
