### ISSUE TITLE
[BUG] Text overlaps in some situations

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#2655] opened 2022-07-16 21:00 UTC
**Description:**
On some routes and in some trainer battles, the name of the route/name of the trainer will overlap with the name of the pokemon being battled.

**Steps to Reproduce:**
An easy and consistent way to replicate is to go to Sinnoh Route 205 and find a Gastrodon (west), and you'll see the name of the route in the top left overlap with the name of the pokemon.

**Expected Behavior:**
Expected behavior would be that the text would not be able to overlap.

**Screenshots:**
![Screenshot_37](https://user-images.githubusercontent.com/36621129/179371651-f8db79e7-c72e-45c2-8faa-5092e4e422a5.png)
![image](https://user-images.githubusercontent.com/36621129/179371687-bccb5408-8bb0-4d63-b0f1-3b654046e242.png)

**Comment by Jaaslet** [comment] 2022-08-06 16:09
Closing as a duplicate of #1619

**Closed by Jaaslet** 2022-08-06 16:09 UTC
Labels: bug
