### ISSUE TITLE
[BUG] Refreshing the game gives a different passive attack power

### ISSUE THREAD

**Issue by minisephirot** [pokeclicker/pokeclicker#2904] opened 2022-08-26 14:29 UTC
**Info**
 - OS: Windows 10 21H2
 - Browser : Firefox
 - Version : 0.9.12

**Description:**
Hi everyone, I've been seeing this behaviour sparsly while playing the game (wich is great by the way) :

I've observed that my passive attack was getting low and lower the more I've left the game running. Refreshing seems to undo this effect.

Example -> I'm progressing on Unova road 9 :
![image](https://user-images.githubusercontent.com/22344585/186923253-20df1ba4-9f4d-4798-bedc-09acc08aabe1.png)
I'm refreshing the game just to see if this will change anything via CTRL + R 

Reloading the save by refreshing puts me on the same road again, but my pokemon attack rose up :
![image](https://user-images.githubusercontent.com/22344585/186924221-75fd50a9-040c-4a17-94f4-9bec23357979.png)
As you can see, i've slain 12 wild before encountering the same pokemon again, and those 12 does not really explain a bump of 430k of passive attack. (~20%)

Sometimes the plundge gets really hard, I end up at 400k attack on a region, CTRL+R and it goes back to 2 million.
The confusing part is that I have no way to tell if the correct attack power is before the refresh or after..

**Steps to Reproduce:**

1. Play the game, leave the game open for a while (I have hatchery helpers ON)
2. Check the passive attack power
3. Refresh on a road
4. Find the same pokemon (else types/gems are going to mess everything up)
5. Observe a different value

**Expected Behavior:**

Refreshing should not impact on the game calculation

**Screenshots:**

See above

**Additional Information:**

I can upload my save if needed, but since this is a refresh based bug this might not be usefull.

**Comment by PixLSteam** [comment] 2022-08-26 14:41
Your Pokémon were stolen from the Hatchery. Refreshing triggers the temporary solution and gives them back to you.
Duplicate of #2825 #2807

**Closed by PixLSteam** 2022-08-26 14:41 UTC
Labels: bug

**Comment by minisephirot** [comment] 2022-08-26 15:00
I have times were I do not fire helpers, and leave the game open and still bump on refresh from 1M to 2.5M.
It probably should wait until the hatchery bug is fixed right now I can't attribute this to something else with 100% confidence.

**Comment by minisephirot** [comment] 2022-08-29 12:49
@PixLSteam 0 manipulation of helpers :

![image](https://user-images.githubusercontent.com/22344585/187204161-1473f6ca-2664-4f15-af08-3796cb73d4a6.png)
When I refresh :

![image](https://user-images.githubusercontent.com/22344585/187204483-aec2c89b-967b-471f-95f8-281661a6507c.png)

If this was an hatchery bug, how does firing three helpers (and loosing three pokemon from the pool) can make one loose 3M damage ?

**Comment by RegisCoaxans** [comment] 2022-08-29 13:03
The current hatchery bug has nothing to do with helpers. Pokemons get counted as breeding at some point but sometimes never get counted down thus they do not participate in the DPS anymore once the bug occurs on them. 
Refreshing is only a hot fix which resets the breeding status of the Pokemons if not in the hatchery or in the queue and restore your damages.
