### ISSUE TITLE
[SUGGESTION]: Shadow Lugia & pokemon

### ISSUE THREAD

**Issue by DuhKingConor** [pokeclicker/pokeclicker#3937] opened 2023-02-13 20:46 UTC
### Current Behavior

Does not mention, or do anything with shadow pokemon.

### Improved Behavior

A limited time event, or even a new region (or sub-region if that’s easier) Orre, that involves shadow pokemon and lugia.

### Reason for change

Adds alternate forms for some pokemon and a cool new region.

### Detailed Description

There are 131 Pokémon that had shadow forms (including lugia). I think it would be cool to add them to the game somehow. Currently lugia is the only one that turns all black. Maybe you could either make custom sprites for them all to be black, or just have the shadowy aura around them. There are a few legendaries and pseudos that could be dungeon bosses. I feel like this area could be similar to sevi 4567 with pinkan/valencian pokemon. So dungeons and gym, and it’s own quest line.

Or a limited time event around the release date of the game (Aug 4 for Japan to Oct 3 for USA. Australia and Europe were released in Nov). During the event, all 131 Pokémon are replaced with shadow versions (or at least a large chance to find them) in the same routes/dungeons you normally find them in.

**Comment by PixLSteam** [comment] 2023-02-13 20:48
Duplicate of #1424

**Closed by PixLSteam** 2023-02-13 20:48 UTC
Labels: suggestion
