### ISSUE TITLE
[BUG] gastly missing 

### ISSUE THREAD

**Issue by Baptoulinou** [pokeclicker/pokeclicker#2216] opened 2022-05-23 12:37 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by dragonkin550** [comment] 2022-05-23 12:40
I'm not a dev, but here's what'll happen if you don't finish filling out the form: A developer is going to ask you to re-submit this ticket with the fields properly filled out, and then close this ticket.

**Comment by amative1** [comment] 2022-05-23 12:46
Or better yet: Gastly is in the game. Not a bug.

**Closed by amative1** 2022-05-23 12:46 UTC
