### ISSUE TITLE
"Caught Unique Pokemons By Region" only having Kanto region even after unlocking other regions [BUG] 

### ISSUE THREAD

**Issue by Pyrii** [pokeclicker/pokeclicker#1386] opened 2021-05-04 17:04 UTC
I've moved past the Kanto region (Now into Sinnoh) yet still don't have extra achievements unlocked for catching unique Pokemon by each region making it hard to tell when I have enough to move on.

![urCe3ZF 1](https://user-images.githubusercontent.com/932782/117041805-2314b980-ad03-11eb-9f4d-61e77ca32bb2.png)

**Comment by Qwertypop4** [comment] 2021-05-04 17:14
Not a bug

**Comment by anapple96** [comment] 2021-05-10 09:24
Close this, as it's an intended mechanic, as the achievements for later regions aren't added yet

**Closed** 2021-09-08 01:43 UTC
Labels: bug
