### ISSUE TITLE
Game save wont load

### ISSUE THREAD

**Issue by James2883** [pokeclicker/pokeclicker#5396] opened 2024-06-30 21:31 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

My save that I downloaded will not load into the game please fix this.Like it just loads indefinitley.

### What did you expect to happen?

For the save to load.

### Steps to Reproduce

1. load save 2. close tab 3. download save 4. load save 5. see the bug for yourselves

### What operating system are you using?

Acer/Windows

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
F12 only opens a new tab
```

### Additional Information

None

**Comment by Askellown** [comment] 2024-06-30 21:50
Duplicate of #5339 
fix shared in <https://github.com/pokeclicker/pokeclicker/issues/5339#issuecomment-2177195623>

**Closed** 2024-07-09 06:41 UTC
Labels: bug
