### ISSUE TITLE
[SUGGESTION] Hatchery sort/display values should factor in effort value attack bonus.

### ISSUE THREAD

**Issue by z5002800** [pokeclicker/pokeclicker#2605] opened 2022-07-09 12:39 UTC
As in title, hatchery sort/display values should factor in effort value attack bonus, so that sorting by "breeding efficiency" and "attack bonus" and similar should be based on actual effect, rather than effect before effort values are considered.

**Current Behavior**
When using filters, sorting, and similar for categories like "breeding efficiency", "attack bonus", and similar, the raw attack bonus value is used.

**Improved Behavior**
Instead of raw attack bonus value being used, this value should be multiplied by effort value bonus, and any derived sort orders or displayed values should use this change in the base value.

**Reason for change**
As there is great variance in how difficult it is to raise the effort values of a particular pokemon, this bonus is likely to be greatly different between Pokemon who would otherwise have similar breeding efficiency. Due to this, the relationship between raw attack and damage dealt, even before considering encounter-specific factors like typings, varies greatly between Pokemon, therefore making the current way of sorting the hatchery list extremely misleading.

For example, the top 4 Pokemon currently when fully fed with proteins are Gyarados, Phione, Manaphy, and Magikarp, who in these conditions have efficiency 9, 8.1, 8.1, and 7.5 respectively. Of these, Magikarp is one of the most common Pokemon to find in the wild across many locations, and the easiest to increase the effort values of. Then, Gyarados can be found in various locations, although less locations than Magikarp, so is somewhat less easy to raise effort values for. Next, Manaphy can only be found as a roaming Pokemon, and so is significantly harder to raise the effort values for. Finally, Phione, to my knowledge, cannot be found in the wild anywhere, and so currently cannot have effort values raised at all. Therfore, Magikarp may at times overtake Gyarados prior to both being fully EV trained, and will almost certainly greatly overtake Manaphy for most players, potentially permanently, while even Pokemon roughly half as efficient, such as Marill, will eventually and permanently overtake Phione, who cannot be EV trained at all.

With this change, by EV training Pokemon, they would be brought higher up in the breeding efficiency list, with a number to better represent the increase in damage by breeding them displayed, allowing players and hatchery helpers to more effectively choose which Pokemon to breed based on actual current benefit, rather than what would have been the benefit if the EV system did not exist at all, or what would happen if it was feasible or possible to EV train every single Pokemon in the game.

**Detailed Description**
- "Attack Bonus" should be changed from 0.25 * Base Attack + Proteins Used to (0.25 * Base Attack + Proteins Used) * EV Bonus, and potentially renamed to "Damage Bonus" to reflect the change.
- "Breeding Efficiency" should use the new way of calculating "Attack Bonus" as it's numerator, instead of the old way.
- "Steps per Attack Bonus", similarly, should use the new way of calculating "Attack Bonus" as it's denominator, and renamed to match if Attack Bonus is renamed.
- "Attack" sort should either be replaced with "Damage", or "Damage" should be added as a seperate option.

**Comment by pjeanjean** [comment] 2022-07-09 16:20
I agree for the most part, but I think it should be a setting (similar to the region debuff on the develop branch).
The reason is that the bonus provided by EVs is retroactive, which means by some might prefer to optimize breeding without considering EVs and farm them later (which makes even more sense with the future plans of adding other EP sources).

**Comment by Jaaslet** [comment] 2022-07-09 16:35
They will be included in all the numbers in the next update.
This was intended all along.
It's already merged, so i will close this issue

**Closed by Jaaslet** 2022-07-09 16:35 UTC

**Comment by z5002800** [comment] 2022-08-01 21:05
Hey just want to follow up, this doesn't appear to be part of the behaviour in the current update, is this still planned?
