### ISSUE TITLE
[SUGGESTION] Farm Overlay // Pokeballs' Categories selection

### ISSUE THREAD

**Issue by Gazareck** [pokeclicker/pokeclicker#2597] opened 2022-07-08 08:57 UTC
Hello,
I have 2 small suggestions for improving the IG experience. 
1. One is regarding the player's view of the **farming tool**. 
2. The second one is about giving more possibilities of **personalization of the Pokeballs usage**, since the last updates added a new feature (Pokérus)

**Current Behavior**
1. Currently, the navigation panel of the farm tool moves in line with the number of bays displayed on the page. if there are fewer berries displayed as on page 9, the navigation arrows, shovels and "harvest" button go up and it is not practical when changing pages.
2. Current situation of pokeballs allows us to choose for 4 categories : Caught, Caught shiny, New, New shiny. Since the game was updated and pushes us to catch more and more pokemons to boost EVs, I think that this has to be adapted.

**Improved Behavior**
1. See screenshots. If possible to hold the panel at the bottom of the page. I also think that MANY changes are necessary for the farm such as categories for berries for people who uses different farming setups (shinies, egg steps boost, roamings...)
2. I think it is necessary to improve the pokeballs feature by giving the player the possibility to set categories for the pokemons that the player wants to catch. For example using the "Category" system that is already existing in the hatchery so people could select pokemons that they want to catch without having to use the pokeballs for all the other unwanted pokemons of the road/dungeon. For example right now it is absolutely impossible to catch a roaming pokemon that we already have without keeping the "Caught" category 24hours activated. 

**Reason for change**
1. Makes the experience more practical when navigating a lot in the farming tool when we click fast it's disturbing to go down and up between page 9 and 10.
2. Capture some pokemons that we already have without having to capture all the others is a pain, even more for roaming which are actually almost impossible to get

**Detailed Description**
1. Description is shown on screenshot + explained in "Improved behaviour".
2. Add the possibility to set categories for the Pokéballs, with the same system from the hatchery. I can create a category "Best Pokemons" and capture only those I select with Hyperball, I could also create another Category with "Roamers" and choose to capture with a Masterball each time a roamer appears.

**Screenshots:**
1. Farm suggestion
![current farm](https://user-images.githubusercontent.com/108922124/177951395-8c2176a3-276d-44e7-9faa-a11c95aeb161.jpg)
![suggestion for farm](https://user-images.githubusercontent.com/108922124/177951398-d0d0a012-fb87-43b7-ab1b-c0954305aabf.jpg)

2. Pokeball system
![pokeballs suggestion](https://user-images.githubusercontent.com/108922124/177956194-16940ab7-1275-41fc-b1d1-cd86c02f047d.jpg)

Thanks a lot for your attention and your help.

Regards

**Comment by Jaaslet** [comment] 2022-07-15 11:44
It's confusing when there are two issues in one. Like now i want to close the pokeball thing as a duplicate of #1712, but can't without closing the farm one.
I like the farm part and think we should change it, but it needs to have it's own issue.
I will close this one

**Closed by Jaaslet** 2022-07-15 11:44 UTC
