### ISSUE TITLE
[BUG] Already completed achievements shown as incomplete

### ISSUE THREAD

**Issue by yukarin-san** [pokeclicker/pokeclicker#2381] opened 2022-06-05 10:53 UTC
**Info**
 - OS: Windows 7
 - Browser Chrome Build 100.0.4896.127 64bit
 - Version v0.9.5

**Description:**
Already completed achievents are shown as incomplete although achievement progress is 100% (see screenshot). This behaviour was not observed in the previous version.

**Steps to Reproduce:**

1. Go to Achievement List
2. Click on Status: Incomplete
3. Sort by Progess descending
4. See achievements which were already completed

**Expected Behavior:**
The achievements should be in the completed list, counted towards the achievement bonus.

**Screenshots:**
![image](https://user-images.githubusercontent.com/106910943/172046989-0c2d26b1-03ba-4c3c-8457-746f5c54fd04.png)

**Comment by Ultima1990** [comment] 2022-06-05 10:57
Duplicate of #2280

**Closed by Ultima1990** 2022-06-05 10:57 UTC
Labels: bug
