### ISSUE TITLE
[SUGGESTION] Additionnal Pokémon List option to see attack with region penalty factored in

### ISSUE THREAD

**Issue by Katalysor** [pokeclicker/pokeclicker#1876] opened 2022-03-16 14:54 UTC
It would be really appreciated to have an option in the Pokémon List that allows to see the attack of the Pokémons with the region penalty factored in.

**Comment by Qwertypop4** [comment] 2022-03-16 15:10
The damage calculator allows you to do this

**Comment by Farboo171** [comment] 2023-05-05 00:44
Duplicate of #511, closing

**Closed by Farboo171** 2023-05-05 00:44 UTC
