### ISSUE TITLE
[SUGGESTION]: Additional Loadouts for Oak Items

### ISSUE THREAD

**Issue by agent-fizz** [pokeclicker/pokeclicker#3468] opened 2022-11-24 21:26 UTC
### Current Behavior

Currently: Oak Items are able to be assigned to up to three customizable loadouts. These loadouts are convenient and allow for easy swapping between tasks. 

### Improved Behavior

I would like to have more loadout slots available, perhaps up to five or six? These would be unlocked by story progression or by # of Oak Items unlocked (or even could be tied to # of Oak Items upgraded). 

### Reason for change

There are many Oak Items that are not used at all in the overworld. I would like to have the ability to have three loadouts for Overworld tasks, with one loadout each for Farm and Underground. 

### Detailed Description

![pkclicker](https://user-images.githubusercontent.com/119011844/203865011-c8c94c2d-ee04-44f2-a065-b126713308e2.png)

Additional slots for loadouts would have minimal to zero impact on game balance, and would allow for more flexible use of existing game mechanics. 

The loadout format already exists; this does not require implementation and testing of a new system. 

This rewards players who pay attention to each Oak Item's benefits, but does not punish players who are suboptimal. 

Tying loadout slots 4 & 5 to game progression in some way (such as leveling Oak Items or the purchase of additional Oak Items) would keep options simple until new players had progressed far enough in the game. 

In addition, this would allow for easier implementation of future Oak Items should the game have need of them.

**Comment by PixLSteam** [comment] 2022-11-24 21:28
Duplicate of #1312

**Closed by PixLSteam** 2022-11-24 21:28 UTC
Labels: suggestion
