### ISSUE TITLE
[SUGGESTION] Pokeclicker Region Prestige.

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [pokeclicker/pokeclicker#1671] opened 2021-12-11 14:40 UTC
I like my usual click attack, but I would like to increase it more by Region Prestige.
Region Prestige will reset the Certain Region's Caught Pokemon to Uncaught, but only the Pokemon native to that specific Region.
And there will also be achievements for Region Prestige.
Here is the achievement Format:
Prestige X times in Specific Region
The Prestige Achievements will be from 2% for the minimum Achievement Bonus increase for Kanto to 50% for the maximum Achievement Bonus increase in Kalos, Alola, Galar, Isle of Armor, and Crown Tundra

By the way, Egg hatches are only for Pokemon that come from eggs only.
You also keep all currencies, eggs, fossils, achievements, badges, balls, and old pokemon attack from attack breeding before the region prestige. You keep shinies as well.

**Comment by widrex** [comment] 2021-12-11 14:58
as Apple said on the last thread

No™️

**Comment by amative1** [comment] 2021-12-11 15:01
Duplicate of #1659, can be closed as already rejected by Senior Dev.

**Comment by apple096** [comment] 2021-12-11 15:05
> Duplicate of #1659, can be closed as already rejected by Senior Dev.

Granted, a lot of things I say no/yes to are very subjective. But, it's widely known that the devs don't like prestige, so everyone will probably say no anyway

**Comment by Ultima1990** [comment] 2021-12-11 15:17
Who knows, maybe some day someone comes along with that perfect prestige pitch that makes us all go OMG YES!

This is not that pitch. But, to be very fair, it is in the top percentage of prestige pitches. It has an actual idea of what the system would be. Most prestige pitches boil down to "we should have prestige, why is there no prestige?". Not exactly useful.

**Comment by amative1** [comment] 2021-12-11 15:19
Worth noting that self-closing a suggestion and immediately opening a new suggestion with the exact same text isn't something I'd recommend.

**Comment by RedSparr0w** [comment] 2021-12-11 23:51
Closing as duplicate of #238

Prestige is unlikely to happen before all the regions are released (if at all) as it would be a massive change to how everything in the game works.

**Closed by RedSparr0w** 2021-12-11 23:51 UTC
