### ISSUE TITLE
[BUG] Repeat Attack Achievement Earned with X Attack

### ISSUE THREAD

**Issue by Spetzel** [pokeclicker/pokeclicker#2772] opened 2022-07-28 00:36 UTC
**Info**
 - OS: Windows 10
 - Browser: Firefox
 - Version: v0.9.9

**Description:**
My base attack is 210,000 and an X Attack is enough to push me over the "Have 250,000 Attack" achievement threshold. Every time I close Pokeclicker the achievement un-earns and my Click Attack drops back down. Relaunching Pokeclicker and using another X Attack regains it. The achievement can only be earned once per session.
I don't know if this occurs for other attack achievements.

**Steps to Reproduce:**
1. Have a displayed Pokemon Attack slightly below 250,000
2. Use an X Attack, receive "Have 250,000 Attack" achievement
3. Close Pokeclicker
4. Relaunch Pokeclicker
5. Use an X Attack, receive "Have 250,000 Attack" achievement

**Expected Behavior:**
Either for X Attacks to not affect achievements or for it to work one and done.

**Screenshots:**
None

**Additional Information:**
None

**Comment by Jaaslet** [comment] 2022-08-01 08:52
Closing as a duplicate of #2351

**Closed by Jaaslet** 2022-08-01 08:52 UTC
Labels: bug
