### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FacundoDans** [pokeclicker/pokeclicker#3124] opened 2022-10-06 14:31 UTC
**Info**
 - OS: Windows 10
 - Browser Opera gx
 - Version 0.9.16

**Description:**
in the search "pinkan theme park" asks to find 10 "pixie plates". While I had that part active I inadvertently sold 15 and the value changed to -15/10. yesterday I found 1 on the dig floor and I passed the value to -14/10

**Expected Behavior:**
don't count negative numbers

**Screenshots:**

![bug-img-ptp-quest](https://user-images.githubusercontent.com/111793845/194340502-de2460f3-d722-4018-a379-8f90d045fe85.png)

**Comment by PixLSteam** [comment] 2022-10-06 14:34
Duplicate of #3123

**Closed by PixLSteam** 2022-10-06 14:34 UTC
Labels: bug
