### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by simcowking** [pokeclicker/pokeclicker#4481] opened 2023-07-04 15:51 UTC
### Current Behavior

Color Coding routes work from top to bottom. If one is set to transparent all items below are ignored.
Ex: Setting missing shiny to white ignores all filters below (missing resistances)

### Improved Behavior

A way to manually rearrange the coloring of the routes would be ideal similar to the pokeball filters. With an option to completely disable a filter color if desired (ex never look at quests for coloring)

If I want to see all routes with resistances I could drag it above the shiny coloring. If I never want to see a route with a quest colored green, I could disable it completely.

### Reason for change

My opinion is getting resistances (on certain routes/dungeons) is slightly easier than all the shiny pokemon. Would be nice to be able to clear all the resistances out when possible with a quick glance without having to either idle on a route hoping to see all the available pokemon or loading the wiki and pokedex to compare.

The filter out quests is just an add on thought if possible.

### Detailed Description

![image](https://github.com/pokeclicker/pokeclicker/assets/138606129/dd45c768-ec1a-49ee-a293-8f4702d2e829)

In this image you can use the dots to rearrange the filters (top to bottom). if I click the blue thing it'll be ignored in the coloring sequence.

**Comment by PixLSteam** [comment] 2023-07-04 16:00
Duplicate of #3944

**Closed by PixLSteam** 2023-07-04 16:00 UTC
Labels: suggestion
