### ISSUE TITLE
[Bug]: dmg stopping over time in pokeclicker

### ISSUE THREAD

**Issue by whiteted** [pokeclicker/pokeclicker#4861] opened 2023-11-03 01:09 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When i play a certain time, my game stop doing damage when i m on the page and when i m out the page, it s working sometimes
![pokeclicker](https://github.com/pokeclicker/pokeclicker/assets/149742140/3b0ab073-d5fc-4215-bcf6-430da367e7c3)

### What did you expect to happen?

Can somebody tell me what to do in order to fix it ?

### Steps to Reproduce

1. Play pokeclicker.
2. At some point, the pokemon wont deal damage and the game feels like it s frozen

### What operating system are you using?

windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by Qwertypop04** [comment] 2023-11-03 01:13
Turning off your scripts will maybe help. Since you are playing the game with cheats, I'm gonna assume they are the cause and close this.

**Closed by Qwertypop04** 2023-11-03 01:13 UTC
Labels: bug

**Comment by jpaillet01** [comment] 2023-11-03 07:25
u used script, wich are not autorihzed on the game, so u wont get any help
