### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by arcaneflamboyant** [pokeclicker/pokeclicker#2304] opened 2022-05-28 17:12 UTC
I wish I could help translate your game into French

**Comment by Someonealive-QN** [comment] 2022-05-28 17:15
One of the developers has a wip for and :
![Screenshot_20220519-145103](https://user-images.githubusercontent.com/97617298/170835756-a568c22d-9c05-4a07-8c69-8c1d45120c6a.jpg)

**Comment by PixLSteam** [comment] 2022-05-28 17:17
Duplicate of #2195

**Closed** 2022-05-28 17:23 UTC
