### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pedobear0** [pokeclicker/pokeclicker#2863] opened 2022-08-17 10:32 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.9.10

**Description:**
Impossible to finish "Ultra Beast Hunt" quest

I captured the demanded Ultra Beasts but the quest is still active

**Screenshots:**
![image](https://user-images.githubusercontent.com/111429165/185097742-ec4f1e30-79d1-4b7d-bb0e-c746d98f01da.png)

**Comment by PixLSteam** [comment] 2022-08-17 10:39
Duplicate of #2804 #2856

**Closed by PixLSteam** 2022-08-17 10:39 UTC
Labels: bug
