### ISSUE TITLE
[SUGGESTION]: Beedrill is stronger than Mega Beedrill

### ISSUE THREAD

**Issue by Blacksonic57** [pokeclicker/pokeclicker#5563] opened 2024-09-27 16:42 UTC
### Current Behavior

How can it be that the mega evolution is weaker?

### Improved Behavior

Reversing their stats would suffice I think

### Reason for change

An upgrade has to be stronger than his predecesor

### Detailed Description

I propose to invert their stats between them and it will be logic.

**Comment by PixLSteam** [comment] 2024-09-27 16:45
Duplicate of #4428

**Closed by PixLSteam** 2024-09-27 16:45 UTC
Labels: suggestion
