### ISSUE TITLE
[BUG] Route Restriction Bypass

### ISSUE THREAD

**Issue by GamingAntiBug** [pokeclicker/pokeclicker#2184] opened 2022-05-18 03:14 UTC
**Info**
 - OS: All
 - Browser: All
 - Version 0.9.3

**Description:**

When you use the hotkeys to go forwards and backwards between routes (defaults are - and +/=) if you only need to defeat more pokemon on previous routes, it will simply let you go. However, any pokemon defeated will not count towards achievements or the x/10 limit for the next route once you leave. 
**Steps to Reproduce:**

1. Go anywhere in a region that you still have locked routes on that can be unlocked by defeating 10 pokemon on a previous route. 
2. Press your hotkey to move up a route until you get in.
3. You are not into the next route

**Expected Behavior:** 
"You do not have access to that route yet. (Current region) route (previous route) still needs to be completed." Message, letting you know that the route is still blocked, and what route needs to be completed to unlock it.
**Screenshots:**

None necessary.

**Additional Information:**

No additional problems, but please feature me in the credits lol.

**Comment by NiCeDiCe90** [comment] 2022-05-19 12:24
I can't reproduce this bug... Can you tell us at which route this happens exactly?

![grafik](https://user-images.githubusercontent.com/82889773/169292462-8c4aefa2-0f7c-4602-871e-e7ce8dc6d927.png)

**Comment by Jaaslet** [comment] 2022-08-06 16:15
This bug can still not be reproduced. I will close the issue

**Closed by Jaaslet** 2022-08-06 16:15 UTC
Labels: bug
