### ISSUE TITLE
[SUGGESTION]: all fossils in hatchery queue

### ISSUE THREAD

**Issue by MiniZ26-Nyx** [pokeclicker/pokeclicker#5447] opened 2024-07-19 17:16 UTC
### Current Behavior

the queue is only for breeding

### Improved Behavior

change queue to be breeding and hatchery

### Reason for change

I feel like it would be easier to add type eggs or fossils into the queue instead of waiting for an open space in the hatchery

### Detailed Description

the hatchery/breeding queue would allow not only pokemon to breed to increase their attack, but also the type eggs (eg. water, fire) and fossils (eg. dome fossil, jaw fossil)

**Comment by PixLSteam** [comment] 2024-07-19 17:25
Duplicate of #1362

**Closed by PixLSteam** 2024-07-19 17:25 UTC
Labels: suggestion
