### ISSUE TITLE
[SUGGESTION] New pokeball selection option for "rare" mons

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#2635] opened 2022-07-14 06:10 UTC
**Current Behavior**
There are 4 options you can set a default pokeball to use when a specific type of pokemon is encountered. (Caught, Caught Shiny, New, and New Shiny)

**Improved Behavior**
A 5th option that lets you set a pokeball to be used when trying to catch a Roamer, Legendary, or Dungeon boss.

**Reason for change**
With the addition of EVs that can only be obtained from catching more of the same pokemon after spreading Pokerus to your own one of that mon, Roamers are difficult to actually get EVs for due to their rarity. It also requires more micromanagement to repeatedly catch legendaries/dungeon bosses as unless you want to spend extra time waiting to catch all the regular mons before you find the dungeon boss, you'll have to switch your default from Caught to an actual ball so you can try to catch it.

**Detailed Description**
Add a 5th option to the Pokeballs tab where you can choose what ball to use by default against Roamers, Legendaries, and Dungeon bosses. A separate option only for shiny roamers/legendaries/dungeon bosses would not be necessary since they would already fall under the captured and uncaptured shiny options but could be added for consistency and would have more niche use.

**Comment by Jaaslet** [comment] 2022-07-15 11:46
Closing as a duplicate of #1712. Please leave a comment on that issue, if you want to add something to it

**Closed by Jaaslet** 2022-07-15 11:46 UTC
