### ISSUE TITLE
[SUGGESTION] Keyboard shortcut.

### ISSUE THREAD

**Issue by seedasantos** [pokeclicker/pokeclicker#1686] opened 2021-12-17 20:24 UTC
**Current Behavior**

Have to click on farm to access.
**Improved Behavior**

Ability to hit F on keyboard to access farm quickly and easily.
**Reason for change**

This would allow people with potential issue using mouse to better access the farm.
**Detailed Description**

**Screenshots:**

**Comment by RedSparr0w** [comment] 2022-02-11 05:16
Closing as duplicate of #1454

**Closed by RedSparr0w** 2022-02-11 05:16 UTC
