### ISSUE TITLE
[BUG] Timer not launching/Only clic attack/Combat not ending correctly

### ISSUE THREAD

**Issue by BENJAMpaix** [pokeclicker/pokeclicker#2273] opened 2022-05-26 11:10 UTC
**Info**
 - OS: Windows 10
 - Browser : Brave
 - Version : 0.9.4

**Description:**
The title is a bit long but it looks like all come as a package : sometimes the game stop the auto-attack and only the clic-attack works. In dungeon, the timer didn't launch itself, there is no attack other than my clics and I can progress until the end like this. But when it occurs vs a champion (or the League), the screen stay "freezed" on the last pokemon defeated with 0 HP. I said "freezed" because I can still click on the map to go to an other road/town/dungeon to progress further as if nothing happened but it counts as "total clears = 0" (and in the case of the League, it unlock the next one all the same)

**Steps to Reproduce:**

I don't know what makes the game stop auto-attacking, but when it's the case :
1. Go to any gym not previously cleared
2. Challenge
3. Wait and see

**Expected Behavior:**
Working as expected

**Screenshots:**

1) Combat ended vs Bruno and I didn't go back to the selection screen of this area 
![Pokeclicker 1](https://user-images.githubusercontent.com/51934051/170473825-8c3fe786-e57a-4756-bb6c-dde0ce61c913.png)
2) I clicked on the "Indigo plateau Johto" on the mini-map, and Karen is unlocked while Bruno is still shown as non-cleared once
![Pokeclicker 2](https://user-images.githubusercontent.com/51934051/170473948-cd379f54-f1a8-427e-852b-a0a0bab4ccc3.png)
For the next two, I clicked on an other page to see if the timer was starting only if I looked somewhere else, and it's what happens
![Pokeclicker 3](https://user-images.githubusercontent.com/51934051/170474496-1f6fd104-ca99-4e3e-b9f8-4c33ce553797.png)
One minute later, nothing has changed
![Pokeclicker 4](https://user-images.githubusercontent.com/51934051/170474505-278b4f6d-30c0-4a90-a01b-cee301a10a5b.png)

**Additional Information:**
The auto-attack stopping is only when the Web page is active. While i'm writing here, the game progress as expected, but when I go back to it, auto-attack stops.
If I go to a dungeon/gym previously cleared, I still have no timer but no issue at the end, and it's rightfully counted. 
If I clear a second time a "bugged" Gym/Leader, then it's counted as "Total clear = 1"

**Comment by Ultima1990** [comment] 2022-05-26 11:13
Duplicate of #2272

**Closed by Ultima1990** 2022-05-26 11:13 UTC
Labels: bug
