### ISSUE TITLE
[Dratini disaspeared after evolving] 

### ISSUE THREAD

**Issue by safeControl1** [pokeclicker/pokeclicker#2395] opened 2022-06-06 17:28 UTC
**Info**
 - OS: [Windows 10]
 - Browser [Opera GX]
 - Version ['v1.0.0`]

**Description:**
After my dratini hatch from the dragon egg and evolve, I lost dratini in my obtained pokemon and stayed with Dragonair. When Dragonair evolved itself, it stayed and give me a Dragonite. The bug was only effective for the first evolution. 
If I buy again the dragon egg, only a Dragonair will hatch. Plus, Make Dragonair ou Dragonite itself hatching as no effet (I add the same bug with nidorina but it reappear by catching it).

**Steps to Reproduce:**
I don't know how to did it because it's not something normal

**Expected Behavior:**
I exepected to have a Dratini, the last pokemon to have, since I bought 8 dragon egg without result, and that I have the proof that i Bought them (Dragonair and Dragonite).

**Screenshots:**
![image](https://user-images.githubusercontent.com/106993237/172213429-f4e2ccc0-8572-4a3d-b709-5d8fe082daed.png)

Thanks for the answer and helping me !

**Comment by Ultima1990** [comment] 2022-06-06 17:29
You sure you didn't hatch Dragonair from that first dragon egg?

**Comment by safeControl1** [comment] 2022-06-06 17:31
> You sure you didn't hatch Dragonair from that first dragon egg?

I'm pretty sure that it was a Dratini and not a Dragonair instantly

**Comment by Ultima1990** [comment] 2022-06-06 17:35
You can hatch Dragonair from the dragon egg. It can be Dratini, Dragonair or Dragonite. This is intentional. So I'm pretty sure that you just got Dragonair. Unless you can prove otherwise I'll consider this not a bug.

**Comment by safeControl1** [comment] 2022-06-06 17:41
I'm sorry I don't really understand what i've failed in the info section, i'm not really familiar with english so maybe I don't saw something.
I don't use external tools, and I did some saves in the past but I don't know if I have a proof that Dratini was on it.

**Comment by Ultima1990** [comment] 2022-06-06 18:10
There is no version 1.0.0. So that can't be right. Please doublecheck everything.

**Comment by NiCeDiCe90** [comment] 2022-06-07 08:49
Thinking about the way the game is coded, can it even be technically possible to lose a Pokémon again? Maybe by reloading before the game autosaved but otherwise I would say it's pretty much impossible...
So 99.999% sure that you got a Dragonair from your egg.

**Comment by Jaaslet** [comment] 2022-06-09 14:30
Will close this issue as it's most likely a misunderstanding. And if it's not, it will be impossible to recreate.

**Closed by Jaaslet** 2022-06-09 14:30 UTC
Labels: bug
