### ISSUE TITLE
[Potential Bug] Dual-Type Damage Calculation

### ISSUE THREAD

**Issue by HateWate** [pokeclicker/pokeclicker#536] opened 2020-01-10 02:28 UTC
**Description:** Upon entering Johto, I've noticed that Dual-Type Pokemon seem to be taking much more damage than Single-Type Pokemon. I'm not sure whether the Damage Formula is being called twice and calculated for each type, or if the Elemental Plate/Shard mechanic is increasing Dual-Type damage in an unexpected way, but it does SEEM inconsistent.

**Expected Behaviour:** The Damage Calculation for Dual-Types should take into account both Types' Weakness and Resistance and their possible overlaps, then run a single Damage Calculation treating the two types as a Single-Type with potential *4 and *.25 modifiers, though I do acknowledge that having to put in and assign formulae for every possible Dual-Typing would take quite some time. Perhaps run a Damage Calculation for each Typing separately, then halve them and add them together?

**Comment by fujnw** [comment] 2020-01-10 05:06
If attacker types are A1 and A2, defender types are D1 and D2, then the damage multiplier is `typeEffect(A1, D1) * typeEffect(A2, D1) * typeEffect(A1, D2) * typeEffect(A2, D2)`. The respective terms are 1 if a Pokemon is single-typed. So as you see, dual types have the potential to deal more damage as well as take more damage, if your shard upgrades are high.

**Comment by danfroese** [comment] 2020-04-22 06:48
Even before maxing shard upgrades, dual-typed pokemon have a significant advantage on the players team, and take significantly more damage. ~2x damage for me right now. A water/poison type will take more damage from a water attack than a pure poison type will if the water's "not very effective" multiplier is above 1.0. This is bizarre. In practice, it means that I prioritize training pokemon who are dual-type, even if a mono-type has almost twice the base attack. And I seek out locations that have few mono-type pokemon for grinding, since I can one-hit dual types with half as much attack. I don't think that this is good for the game, especially because this extreme difference between mono- and dual-type pokemon doesn't exist in the published games.

To solve this weird issue, the solution HateWate describes could work, but it's more complicated, because you can actually have anywhere from x1/16 to x16 with the addition of dual type attacks (for example, a fire/flying Moltres attacking a bug/grass Paras, or a bug/fighting Heracross attacking a flying/poison Golbat). So you'd need to deal with x0, x1/16, x1/8, x1/4, x1/2, x1, x2, x4, x8 and x16. This also doesn't take into account possible differences in shard upgrade levels between the different types of the attacker. 

Averaging the multipliers like HateWate suggests doesn't completely solve this problem either, but it feels a little bit better. With the example of high-ish x0.6, x1.1, x1.6, x2.6 multipliers, a water attack against a mono-poison type (or even a bug/poison type) will do x1.6 damage, and a water attack against a poison/water type will do x1.35 damage. A water attack against a mono-water type will be x1.1 damage. This looks like it could be a step in the right direction, but consider double-super-effective or double-not-very-effective. That same water attack against a water/grass type will deal the same x1.1 damage, despite it being double-not-very-effective, and the water attack against a rock/ground type will be x2.6, ignoring double-super-effective. This might actually be fine for the game though, since type advantages/disadvantages actually don't mean as much in a game where you're attacking with a team full of all types all the time. I also feel like this is probably the best you're going to get without significantly overhauling the shard upgrade system.

Either way, I also think that not-very-effective attacks should not be upgradeable beyond x1.0, and ineffective attacks should be capped at x0.5.

**Comment by Aegyo** [comment] 2020-10-17 16:18
Closing as duplicate of #800

**Closed by Aegyo** 2020-10-17 16:18 UTC
Labels: bug
