### ISSUE TITLE
[SUGGESTION]: Rare Candy on Level 100 Pokemon with Real Evo

### ISSUE THREAD

**Issue by morcousw** [pokeclicker/pokeclicker#5169] opened 2024-03-30 14:22 UTC
### Current Behavior

Rare Candy works as expected in Pokeclicker... it gives 25% base attack whenever it's used.

### Improved Behavior

When playing a Real Evo challenge, as an example, I acquire Nidoking by using a moon stone on Nidorino. However, my Nidoran is level 100 so it won't evolve unless I first hatch it and level it up to the required level. Then it becomes Nidorino and I can go and catch another Nidoran.

In the games, using a rare candy on a level 100 unevolved pokemon will give that pokemon the chance to evolve.

I recommend adding that feature in Real Evo for Rare Candies

### Reason for change

More closely align the Rare Candy behavior with the games. Slight convenience update for Real Evo playthrough

### Detailed Description

See above

**Comment by RegisCoaxans** [comment] 2024-03-30 15:09
Duplicate of #5078.

**Closed** 2024-03-30 15:26 UTC
Labels: suggestion
