### ISSUE TITLE
[SUGGESTION]: Joey re-battles and more alt form rattatas

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4077] opened 2023-04-04 22:27 UTC
### Current Behavior

Joey is a one time April fools event with a single lone boring rattata.

### Improved Behavior

Be able to re-battle joey. Each re-battle gives Joey an additional rattata, even better if they are alt forms of rattata. 

### Reason for change

In GSC, Joey call us all the time to tell us how great his rattata is, Joey also lets us re-battle him after reaching certain cities. 
Joey is a nice damage check for people who are not able to beat him yet. Its a "fun" battle that should not go away after the event. 
We also get to re-battle some rivals after one time battles indefinitely, so why not Joey?

### Detailed Description

Since parts of the game doesn't follow all canon anyways, I propose we fill out certain lines to introduce more rattatas so that joey can travel the pokemon word and be pokeclickers greatest rattata trainer. Rattata is not an over powered pokemon and would not change the breeding efficiency meta game. This would be a fun damage check outside of battle frontier climbing. 
Sure his rattata eventually evolve to raticate in the game, but this is pokeclicker and the rules for canon do not exist.

6 pokemon limit? Joey don't care

**Comment by Jaaslet** [comment] 2023-04-07 10:12
Joey was intended to be an annoying battle, that you are not able to defeat. Adding a permanent annoying battle, might be... too annoying...

**Comment by xslk** [comment] 2023-04-12 03:38
Most people found the battle entertaining, but the haven't seen the reward so it _might_ be annoying after seeing the reward. 

I haven't seen anyone actively hate the battle either other then not being able to challenge him again after the event.

**Comment by Qwertypop04** [comment] 2023-05-03 23:28
Closing as non-canon mons should be avoided without a very good reason, and this PR doesn't actually suggest any Rattata to add, just "more Rattata"

**Closed by Qwertypop04** 2023-05-03 23:28 UTC
Labels: suggestion
