### ISSUE TITLE
[SUGGESTION]: Additional farm(s) that do not produce auras

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#4290] opened 2023-05-11 21:33 UTC
### Current Behavior

We have one farm that is 5x5

### Improved Behavior

Add an additional farm that does not provide aura bonuses.

### Reason for change

People struggling to gather enough berries to EV berrymon or create a farm for aura bonuses no longer have to gimp themselves

### Detailed Description

Create an additional farm or farms (3x3, 4x4 or 5x5 ) that can be unlocked in one of the later regions that provides no aura bonuses. No more struggling to decide if people want to create a farm for actual bonuses to the game or plant berries to EV alcremies and farm wanderers

**Comment by osherwott** [comment] 2023-05-11 22:08
Duplicate of #3298

**Closed by osherwott** 2023-05-11 22:08 UTC
Labels: suggestion

**Comment by xslk** [comment] 2023-05-11 22:09
The duplicate is closed and this one says to not have auras so the balancing headache from the other suggestion wouldn't apply.
