### ISSUE TITLE
[SUGGESTION]: Dungeon Modal

### ISSUE THREAD

**Issue by davidcforte** [pokeclicker/pokeclicker#3952] opened 2023-02-19 20:21 UTC
### Current Behavior

Currently you run dungeons, get carpal tunnel, get loot.

### Improved Behavior

Automatic Dungeon Running/Completion

### Reason for change

Dungeons running is repetitive and not very fun, requiring large amounts of direct input.

### Detailed Description

A Dungeon Modal that unlocks after say... 100? clears of any Dungeon, that allows for some automatic dungeon running. How this would work would be similar in fashion to the Hatchery Modal, where pokemon get removed from your Active Party to function as the Dungeon runners themselves, applying their damage values for the Modal. Auto Dungeon would be a shuffled list of the dungeon tiles completing all of them, then ending on the Boss.
 
- 1-6? slots can be unlocked (cost QP?) for a balanced Dungeon Delver Team. 
- Modal would not have time limit, because you are limited to pokemon on the Dungeon Delver Team
- Your team would pay entrance fee, fight, loot, and complete Dungeons for Achievements, but not catch pokemon that are in the Dungeon
- Possible reward of EVs for the Dungeon Delver Team upon dungeon completions. This provides an Alternate avenue for EV gains, especially for pokemon that have no current ability to gain EVs.
- Require 100? manual clears before Dungeon can be accessed by Modal
- able to turn Repeat on or off, 

![Dungeon Modal](https://user-images.githubusercontent.com/7574359/219973022-646d8618-0a3d-4220-88ba-ba233408e185.png)

**Comment by Farboo171** [comment] 2023-02-19 20:23
https://github.com/pokeclicker/pokeclicker/issues/3470
https://github.com/pokeclicker/pokeclicker/issues/1630
https://github.com/pokeclicker/pokeclicker/issues/1315

**Comment by Farboo171** [comment] 2023-05-04 15:32
Closing as mostly duplicate of #3381

**Closed by Farboo171** 2023-05-04 15:32 UTC
Labels: suggestion
