### ISSUE TITLE
[SUGGESTION] Fill hatching queue

### ISSUE THREAD

**Issue by dassaffe** [pokeclicker/pokeclicker#1911] opened 2022-03-25 10:09 UTC
It would be nice to have an option, to fill up the hatching queue with the current sort + filter-options.

**Current Behavior**
You have to click once for each mon which you are going to breed. This gets more tedious the further you get in the game

**Improved Behavior**
Have a button, which fills the queue with the next [x] pokemon from the list, according to their sorting + filter. 

**Reason for change**
QoL-Change, so you don't have to click 50 times on the same spot, when it could be done with one click

**Detailed Description**
I would love to have a button in the hatching-modal / screen, which simply fills the queue, maybe labeled "fill hatching queue". 

**Screenshots:**
Not applicable

**Comment by RedSparr0w** [comment] 2022-03-25 10:48
Closing as duplicate of #1405

**Closed by RedSparr0w** 2022-03-25 10:48 UTC
