### ISSUE TITLE
[BUG] I didn’t get the safari ticket after fuschia gym

### ISSUE THREAD

**Issue by Piaka9** [pokeclicker/pokeclicker#2268] opened 2022-05-26 09:31 UTC
**Info**
 - OS: Windows 10
 - Browser : [e.g. Chrome
 - Version : v0.9.4

**Description:**
When I want to go to the safari park, I have a message explaining to me that I must have the safari ticket after beat the fuschia gym. But I beat the gym and didn’t get the ticket.

**Screenshots:**
![bug pokeclicker](https://user-images.githubusercontent.com/106308838/170460653-670709be-3bfd-4f03-88ab-49e1337aff03.png)
![bug pokeclicker 2](https://user-images.githubusercontent.com/106308838/170460658-a0ab6269-f880-449d-a468-294079729c8d.png)

**Comment by Ultima1990** [comment] 2022-05-26 09:38
Duplicate of #2267

**Closed by Ultima1990** 2022-05-26 09:38 UTC
Labels: bug
