### ISSUE TITLE
[SUGGESTION] Convert shards into plates

### ISSUE THREAD

**Issue by OlafurKrH** [pokeclicker/pokeclicker#1601] opened 2021-09-16 21:43 UTC
Right now, once a shard type has been maxed out, it's pretty much useless. This should fix that a bit.

**Reason for change**
This will give shards more use, and make it less of a pain to farm them for good trades in the Underground.

**Detailed Description**
To mitigate cheesing shard quests, you can't simply convert 100 shards into a plate, then immediately sell it for the same amount, converting shards into a plate should take at least 1000 shards. Maybe some more for more common types.

**Comment by RedSparr0w** [comment] 2021-09-17 03:59
closing as duplicate of #672
_also related: #1471 #1446_

Feel free to comment there if you have more info to be added.

**Closed by RedSparr0w** 2021-09-17 03:59 UTC
