### ISSUE TITLE
[SUGGESTION] Grand Region Pacing Overhaul

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1416] opened 2021-05-26 20:40 UTC
Pokémon are heavily frontloaded. You start a region with a bag full of stones, eggs and fossils. You can catch watery Pokémon right away. Kingdra _should_ be obtained late in the region. Dragon Scale for sale in Blackthorne. What's the point? Just farm em in Kanto. Get it right away in New Bark. Rekt.

So yeah, this is gonna be a big doc with several ideas on how to spread Pokémon out across the region more.

**Fishing**

This is gonna be the lots of work one. First off, I'd split the rods and add Super. Why aren't we just doing ultra catches anyway? Oh well. Would need something to select the rod. I imagine it'd look something like this:

![RodPicker](https://user-images.githubusercontent.com/69112975/119720654-89a47780-be6a-11eb-857f-f62df885af67.png)

Important thing tho: players *must* always have a rod selected if they have any. Meaning the game will auto select the first rod the player gets, and the player can only choose to select a different rod. They can't choose to have no rod active. Until they enter the next region and have to pick up rods again.
This is because there are certain routes _cough_ Alola _cough_ where fishing encounters are the only possible encounters. TBH I don't actually know what would happen if the player entered a fishing only route with no rod selected, but I imagine it's not nice. Even if it doesn't break the game, I can already see the bug reports. "I'm on route 13 in Alola and no encounters are happening, I am stuck and can't progress, game broken pls fix booo hooo hooo."
Also it'd need to be flexible. There won't always be 3 rods. Unova, Alola and Galar only have 1.

Next, split them further. Region specific rods. This is the main thing. To prevent players from being able to catch all the water pokémon on early routes. No more Sharpedo on 103 from the start. No more easy Quagsire and Qwilfish on 32. Basculin on the very first route? Nope.

So, here's the places that would need to be cleared to obtain each rod:
Kanto: Old rod route 6, Good rod route 15 or 18, Super rod, route 12.
Johto: Old rod route 32, Good rod route 39, Super rod Elite_JohtoChampion (this rod is actually in Kanto).
Hoenn: Old rod Rusturf Tunnel, Good rod route 118, Super rod route 125.
Sinnoh: Old rod route 202, Good rod route 209, Super rod Elite_SinnohChampion
Unova: Super rod route 1
Kalos: Old rod route 8, Good rod route 12, Super rod route 16.
Alola: Fishing rod Brooklet Hill.
Galar: Fishing rod from the start.

I imagine Unova, Alola and Galar would just use Super.
Lets expand this to surfing mons as well. No item for this, they just unlock.

Kanto: Soul badge
Johto: Fog badge
Hoenn: Balance Badge
Sinnoh: Fen badge
Unova: Quake badge
Kalos: Rumble badge
Alola: Brooklet Hill
Galar: Galar_Rock badge

Every time you unlock any of these there should be a pop-up.

**Eggs and Stones**

This is gonna be the unpopular one. No more carrying eggs and stones to a new region. So either: before being allowed to travel, force the player to hatch every egg and use every stone. This also means we have to stop stones dropping in regions where they can't be used. So no metal coats and dragon scales in Kanto. Otherwise this would result in a soft lock. Or just erase them from the player inventory instead.
On the subject of stone drops: I'm not a fan. IMO remove evolution stone drops, or make it so they don't drop until you've owned one. No Kingdra before Blackthorne damn it.
Also, when the player travels to the next region remove all eggs and stones from shops in the previous region. No, you can't just get to the dock, travel back to Kanto and stock up on eggs and stones anyway. That would render this whole exercise pointless.
Perhaps put an NPC early in Kanto to warn players that this is going to happen. Something about strict border laws on eggs and stones for first time travelers. Lets get creative.
All of this applies only when traveling to a new region _for the first time_. Of course you get to keep your stuff when using the dock.

**Fossils**

This is the pain in the ass one. Anorith and Lileep on route 201 is bad pacing. I think the solution might just be to split the underground. Here's how I imagine this working:
Remove underground shortcut, put one on every map. All of these undergrounds would share deals and upgrades, but they have unique item pools and layers. Basically the only difference would be available fossils. Does this mean you could get a fossil early from a deal? Yes. Lucky you. Does this mean there could be a deal you can't do because it needs an item you can't get yet? Yes. Unlucky you. The upside is that it becomes easier to target specific fossils. Need Sail fossil? Go dig in Kalos.

This should spread out the Pokémon across the region a bit more. It truly is my honest opinion that the current situation, where you can fill up so much of a new region's dex on the first couple of routes, is a real problem. This could solve that.

**Comment by NiCeDiCe90** [comment] 2021-05-26 21:58
I like the idea about the fishing rod. 

About Eggs, Evolutions and Fossils... I would take a slightly different route.

Evolutions Stones like firestone etc.: There are just very few Pokemon you can get early with these after Kanto. It's ok imo

Evolution Items that need trading in the original game like dragon scale, metal coat, etc:
Just unlock the evolution by trading first. Set up an NPC in the City closest to the sport where you would actually find the item or wherever it would make sense. Like Olivine for an metal coat > Steelix / Scizor trade or Blackthorn for Dragon scale > Kingdra
Could be combined with some story quests in the future.

Fossils:
The solution to this is very easy in my opinion. Just don't unlock the hatching possibility at the region start. Unlock it after the player reached the spot where the fossils can be magically made into pokemon in the original games.

**Comment by NiCeDiCe90** [comment] 2021-05-27 08:35
Another thing I would like to add but don't know if possible:

Could we limit the max level for regional Pokemon just like in Kanto?
So on entering Johto you can level Kanto Pokemon to level 100 but Johto Pokemon are maxed on level 20 until you get the first badge that raises the max level to 30.

While that stops people from getting every max evolution instantly it also stops them from breeding. So it has to be counter balanced by lowering the regional penalty.

**Comment by Matipou2006git** [comment] 2021-05-31 02:34
so its an super advanced mechanic of the OG game fishing rod item, nice 👍

**Comment by Farboo171** [comment] 2023-05-04 15:40
Closed as partial duplicate of #1183 , partial abandoned project

**Closed by Farboo171** 2023-05-04 15:40 UTC
