### ISSUE TITLE
[SUGGESTION]:  Change Primal Reversions Weather Requirement

### ISSUE THREAD

**Issue by Dragonias** [pokeclicker/pokeclicker#4528] opened 2023-07-15 11:09 UTC
### Current Behavior

Find Captain Stern at Sea Mauville during Thunderstorm Weather

### Improved Behavior

During Rain, Hail or Snow Weather

### Reason for change

Makes the Quest more accessible

### Detailed Description

The reason I suggest this is because at the moment I've seen Thunderstorm either at hours where its just at ungodly times like for example its showed me 4 am (Central Europe Time) and sometimes on Days where no regular working person would have time to check and do such Quests unless they work at home, Theres also the fact that some weeks said Weather just doesnt occur (Screenshot attached for this week) 
![Bild_2023-07-15_130950467](https://github.com/pokeclicker/pokeclicker/assets/69013741/50953c0f-0851-4906-a8ee-466b2b983dff)

**Comment by Tortue2006** [comment] 2023-07-15 11:30
Oh no, there is no thunderstorm, guess people shall wait.

Also, everyone has the problem of the time, since it’s based on your local time. And because that questline isn’t required, I highly doubt this suggestion will get accepted just for the sake of making the questline easier.

**Comment by xslk** [comment] 2023-07-15 11:42
#4246 would make it more accessible if or whenever its merged

**Comment by Farboo171** [comment] 2023-07-17 08:27
This is as intended; sometimes alt forms are hard to get. As slk says, changes may be made to weather, but the quest shall stay the same. Closing.

**Closed by Farboo171** 2023-07-17 08:27 UTC
Labels: suggestion
