### ISSUE TITLE
[SUGGESTION]: 

### ISSUE THREAD

**Issue by pokemonfan111** [pokeclicker/pokeclicker#4288] opened 2023-05-11 15:29 UTC
### Current Behavior

do have a special day for one pokemon example community day

### Improved Behavior

have at least one a month a day where they increst shiny ods on a Pokemon for 1 hour for example Pickatchu

### Reason for change

it would help people how dont have the shiny or pokemon and it would make the game more fun 

### Detailed Description

when the event is on you will get for example you can get extra coins for catching the Pokemon or étra dungeon coins also one day before the event you can buy at any shop a special task that would give the evolved form shiny if have any

dont jug my writing plz 
thanks

**Comment by PixLSteam** [comment] 2023-05-11 17:52
Duplicate of #3730

**Closed by PixLSteam** 2023-05-11 17:52 UTC
Labels: suggestion
