### ISSUE TITLE
[Bug]: Zero Ambition Spooky Plates

### ISSUE THREAD

**Issue by nspjvlac** [pokeclicker/pokeclicker#3884] opened 2023-01-30 00:11 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Zero's Ambition requires you to acquire one spooky plate and 500 ghost gems. I got the spooky plate but I then went to underground and did a "sell all", which converted all my plates into gems. all 600+ of each type. Consequently, the spooky plate counter went into the negative, -601. I am able to increase the count by finding more new ones.

### What did you expect to happen?

I would expect the spooky plates (and indeed any item counter for a quest) to be only allowed to be 0 or a positive integer, not a negative integer. 

### Steps to Reproduce

1. get to zeros ambtion quest
2. Have spooky plates in your underground stocks
3. acquire the single spooky plate you need for the quest
4. before completing the quest, sell your spooky plates from the underground using the sell all option
5. ????
6. Profit

### What browsers are you seeing the problem on?

Desktop Client

**Comment by CooldudeOmega** [comment] 2023-01-30 00:12
very commonly reported bug, no fix yet though, duplicate of something probably

**Comment by Someonealive-QN** [comment] 2023-01-30 00:13
you can fix it by refreshing the game i believe

**Comment by nspjvlac** [comment] 2023-01-30 00:15
closed because its been reported before

**Closed** 2023-01-30 00:15 UTC
Labels: bug
