### ISSUE TITLE
[BUG] Pokemon Disappeared - Magmar

### ISSUE THREAD

**Issue by YthelFR** [pokeclicker/pokeclicker#2773] opened 2022-07-28 07:19 UTC
**Info**
 - Windows 10
 - Firefox
 - v0.9.9

**Description:**
Don't see Magmar in my Pokemon list, i already captured it several times and i'm at Johto now. Maybe disappeared with Hatchery.

**Comment by DataCrusade** [comment] 2022-07-28 07:23
Are you using any scripts? Not trying to shame you and you're not gonna get in trouble for using them lol, but we're currently struggling to identify if this is happening normally or if it's being caused by scripts, since none of us can replicate it.

**Comment by YthelFR** [comment] 2022-07-28 07:26
Nope, i'm not using scripts, my Pokemon just disappeared alone ^^ Maybe he didn't like me :'(

**Comment by lenormandSeb** [comment] 2022-07-28 07:48
Have you a screen from your pokedex with magmar, the pokemon list (order by pokemon and where jinx, electabuzz and scyther are) and hatchery list (again order by pokemon and etc) please 🤔

**Comment by YthelFR** [comment] 2022-07-28 07:54
Sure ! 

Pokedex - List - Hatchery

![magmarpokedex](https://user-images.githubusercontent.com/110157294/181452097-a5b874f6-7344-4301-9b8d-c1c8ab163245.jpg)
![magmarlist](https://user-images.githubusercontent.com/110157294/181452096-2771cd0b-ddcd-4506-94b2-d862dbda13c3.jpg)
![magmarhatchery](https://user-images.githubusercontent.com/110157294/181452089-c7e28cd4-78ad-4d36-8d45-8437458581e8.jpg)

**Comment by YthelFR** [comment] 2022-07-28 07:57
Seems the same for Tauros too o_O Don't have his egg in my Hatchery actually and see it nowhere.

It's like they disappeared when i begun Johto.

**Comment by YthelFR** [comment] 2022-07-28 09:44
Well, there is a list of pokemon missing in my list now :

- Clefairy
- Muk
- Kangaskhan
- Magmar
- Tauros

I have Sam, Blake and Parker in Helps and recently i have Dakota.

**Comment by NiCeDiCe90** [comment] 2022-07-28 09:49
do you have a current save and maybe an older one where they still existed?

**Comment by Ultima1990** [comment] 2022-07-28 09:49
Duplicate of #2770.

**Closed by Ultima1990** 2022-07-28 09:49 UTC
Labels: bug
