### ISSUE TITLE
Eggs in hatchery queue

### ISSUE THREAD

**Issue by MewIstheBest** [pokeclicker/pokeclicker#3133] opened 2022-10-08 17:20 UTC
What I would like to see in the latest pokeclicker update are eggs in the hatchery queue, the benefits of this are if you are planning on completing the kanto shiny pokedex but already on alola then it will be a lot harder to get egg exclusive shinys, which is why I think eggs should be in the Hatchery queue to make it easier for shiny Pokémon to be hatched if there in the hatchery queue

**Comment by PixLSteam** [comment] 2022-10-08 17:54
Are you suggesting the ability to put shop eggs into the queue? If so:
1. What? Why would you buy eggs to go for specific shinies? You know you can just breed them normally, right? Especially since Kanto Pokémon will be incredibly rare once you're in Alola.
2. Duplicate of #1362
If you're talking about something else, feel free to specify what you mean and reopen this issue. I will close it for now.

**Closed by PixLSteam** 2022-10-08 17:54 UTC
