### ISSUE TITLE
[Bug]: exp share unavailavle

### ISSUE THREAD

**Issue by Abrian123** [pokeclicker/pokeclicker#4827] opened 2023-09-29 05:24 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I've been playing the game for a while now, in Unova preparing to go to Kalos, but I still can't figure out why I don't have my exp share available to me. 
![no exp share](https://github.com/pokeclicker/pokeclicker/assets/146412326/aba2877c-9a38-45cd-8a6b-f0295f49b0db)

### What did you expect to happen?

You're supposed to get your exp share after you catch 50 pokemon, but I dont currently have the exp share, and I'm in Unova.

### Steps to Reproduce

I have no way to reproduce this bug, I think it may be a specific thing I missed?

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

**Comment by Aegyo** [comment] 2023-09-29 05:26
disable ad block

**Comment by Qwertypop04** [comment] 2023-10-08 18:37
closing as this is caused by overzealous ad block and therefore not something we can really fix

**Closed by Qwertypop04** 2023-10-08 18:37 UTC
Labels: bug
