### ISSUE TITLE
[SUGGESTION]: Pokeball use category for roaming pokemon

### ISSUE THREAD

**Issue by helioboros** [pokeclicker/pokeclicker#3529] opened 2022-12-05 19:15 UTC
### Current Behavior

At present, we are only allowed to choose pokeballs to use on caught, uncaught, caught shiny, and uncaught shiny.

### Improved Behavior

I would like to see a category for roaming pokemon.

### Reason for change

Someone might like to use Pokeballs for regular route mon catching, and Ultraballs or Masterballs for roamers. Additionally, if someone is grinding for roamer EVs, this would cut out the rabble and allow them to focus on that - or just do something as I'd like to casually do and apply pokeballs to regular route mons and Great balls to roamers.

### Detailed Description

![image](https://user-images.githubusercontent.com/37154824/205723289-97689a4a-b61f-4f01-bee3-cadccc192acd.png)
Something along the lines of a fifth category here.
It could be unlockable after the player catches their first roaming pokemon.

**Comment by jk13pclick** [comment] 2022-12-05 19:16
Duplicate of #1712

**Closed by jk13pclick** 2022-12-05 19:16 UTC
Labels: suggestion
