### ISSUE TITLE
[SUGGESTION] Add Secret Bases and Add Rewards like Statues or Dolls to Put In Them

### ISSUE THREAD

**Issue by CARSOR876** [pokeclicker/pokeclicker#3029] opened 2022-09-21 20:29 UTC
**Current Behavior**
There is no Secret Base mechanic in the game right now

**Improved Behavior**
Add Secret Bases, making one free in every region, one cheap, and the rest very expensive. Every Secret Base that is owned will allow the player to equip 1 statue, doll, or other reward, giving a certain buff depending on what is equipped

**Reason for change**
This could be a very small way to gain buffs that could help the player, but not gain an advantage too big to get ahead of the game

**Detailed Description**
The Secret Bases would appear on a few routes in each region (maybe 5-8?) and allow the player to equip statues, dolls, or any other reward that could be in this category. As stated above, every region would give one of these bases for free, one would be a cheap option, and the rest would be very expensive, basically locked until after beating Alola if the player doesn't completely stop to get it. Statues could be items that are found in the Underground, similarly to Pokémon BDSP. They could give you an extra 3% catching chance towards the type the statue represents, and finding a shiny statue like in the game would give a 5%. You can only have one of each type equipped, and duplicates could be sold for some diamonds. I was thinking 5 for normal and 10 for shiny, but it depends how rare they would really be. Dolls would be able to be bought in a new shop at the Battle Tree that started growing, and these would give the type they represent extra attack. I don't know what amount would be worth it but still be balanced, so I won't suggest a number. And there could be a few other types of things as well, including something like Roaming Pokémon encounter rate up and catch rate up, no matter the type they are. There is plenty more I have thought of for this idea, but this is already a lot, so I will stop it here for now

**Comment by Jaaslet** [comment] 2022-09-23 06:15
Duplicate of #848

**Closed by Jaaslet** 2022-09-23 06:15 UTC
