### ISSUE TITLE
Buff Alola

### ISSUE THREAD

**Issue by Blast645** [pokeclicker/pokeclicker#2027] opened 2022-04-16 06:15 UTC
**Current Behavior**
 Alola is incredibly easy to complete compared to kalos grind wise

**Improved Behavior**
Alola should take as much grind if not more

**Reason for change**
because Alola is basically a free region

**Detailed Description**

**Screenshots:**

**Comment by RedSparr0w** [comment] 2022-04-16 06:23
The problem is you've been grinding while you wait for Alola to be released, also there are already changes in the works.

**Comment by ZellHalI** [comment] 2022-04-16 11:57
Personally I didn't grind while I wait for Alola to be released and I also find the region was to easy

**Comment by Ultima1990** [comment] 2022-04-16 11:59
I think the problem is Kalos is too hard.

I made an effort to keep route difficulty relevant by balancing gyms and dungeons around the health of the nearest (difficulty wise) route. Kalos doesn't do that, and especially the health spike at the league is absolutely insane.

**Comment by Morat48** [comment] 2022-04-16 19:18
I agree with Ultima1990. Kalos requires too much grind, especially for the champion and elite 4. Reduce the scaling in Kalos, and that should make the difficulty curve a lot smoother for Alola too (since you'll probably be less powerful going in).

**Comment by ZargoGames** [comment] 2022-04-17 17:13
Yeah I barely beat Diantha before unlocking Alola and I was able to get to the Elite Four without any grinding (but not beat them)

**Comment by Liz-Pay** [comment] 2022-04-21 19:37
> I agree with Ultima1990. Kalos requires too much grind, especially for the champion and elite 4. Reduce the scaling in Kalos, and that should make the difficulty curve a lot smoother for Alola too (since you'll probably be less powerful going in).

Right now you need to increase your DPS by _more than_ 50% going from the 8th Kalos Gym to the First Kalso E4 battle. I think it's a pretty fair call to say that the Kalos Endgame bosses have way too much health relative to the rest of the region.

**Comment by Jaaslet** [comment] 2022-05-22 19:35
Kalos is getting nerfed in #2102, which makes this issue irrelevant. I will close it

**Closed by Jaaslet** 2022-05-22 19:35 UTC
