### ISSUE TITLE
[SUGGESTION] Hissui ideas

### ISSUE THREAD

**Issue by Matipou2006git** [pokeclicker/pokeclicker#2024] opened 2022-04-15 17:33 UTC
hissui would sub-area in sinnoh 

**Current Behavior**

hissui is missing, including noble pokemon and different form pokemon
**Improved Behavior**

My idea is to create a sub area in sinnoh wich would be hissui, and the sub area could be unlock after either beating cynthia, or beating spear pillar/capturing dialga and palkia.
Note: arceus would be unobtainable until volo is beaten in hissui and obtaining the azure flute.
**Reason for change**

adds new pokemons and region, and more game time.
**Detailed Description**

hissui would be separated in 8 area:
Jubillfe village- town
Obsidian Fieldlands.- area
Crimson Mirelands,-area.         diamond clan-town
Cobalt Coastlands,-area
Coronet Highlands,-area
Alabaster Icelands,-area.        pearl clan-town
Ancient Retreat.-town
to go to another area, you would need to have defeated 100 or 500 pokemon and defeated the noble from that area.

special evolutions and item:
stanler --> wyrdeer:   evolve after lv 25 in obsidian fieldland
(item)black augurite: rare drop in obsidian fieldland
(item) peat block: rare drop in mirelands
ursaring --> Ursaluna: use peat block during night time
hisuian basculin --> basculegeon: lv 30 in cobalt costland
(item) razor claw: rare drop in highlands
hisuian quilfish --> overquill: level 35 in cobalt
petili --> hisuian lilligant: sun stone evolution
goomy--> hissuian sliggoo: evolve at lv 20 in mirelands
hisuian starters: use (new item) on the correct pokemon to evolve them
(new item) hisuian stone: can evolve starter into their hissuian forms
(item) adamant crystal: obtain in diamond clan town after completing hisui questline-used to change dialga form
(item) lustrous globe: obtain in pearl clan town after completing hisui questline-used to change palkia form

(optional): npc that can exange a (type) plate for 10 000 gem(same type)
**Screenshots:**

**Comment by amative1** [comment] 2022-04-15 18:01
Closing as duplicate of #1795, please add any notes there (though also please note that Hisui will not happen until after Alola and Galar are both done, due to multiple reasons).

**Closed by amative1** 2022-04-15 18:01 UTC
