### ISSUE TITLE
[BUG] Achievemento block

### ISSUE THREAD

**Issue by Daegar34** [pokeclicker/pokeclicker#2764] opened 2022-07-26 19:35 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version [e.g. `v0.9.9`]

**Description:**
I've got a bug on a achievement. The achievement " Obtain 10 000 proteins " is blocked at 9 606. Even if I buy, the countdown is block.

**Expected Behavior:**
Perhaps, it's a that I do the process to obtain MissingNo

**Screenshots:**

**Comment by PixLSteam** [comment] 2022-07-26 19:41
Duplicate of #2747, fixed by #2713

**Closed by PixLSteam** 2022-07-26 19:41 UTC
Labels: bug
