### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mugi69** [pokeclicker/pokeclicker#2286] opened 2022-05-27 05:46 UTC
**Info**
 - OS: android
 - Browser chrome
 - Version 

**Description:**
the game proposes me to carry out a quest which is not possible and inconsistent.
The quest is : Defeat the Victory Road Johto dungeon in Johto 16 times 

I have never seen a road to victory in Johto.  In Kanto yes but never on Johto.  I checked anyway but couldn't find anything...

**Steps to Reproduce:**
The quest is proposed by the game…

![C340EDA8-F7D8-4537-A4CB-59FD43E0EF77](https://user-images.githubusercontent.com/106368306/170637915-8046e775-98c2-45be-a333-df8a7e5d8546.jpeg)
![F40B44D6-8163-4EEA-ACCA-C28EE6AC09E7](https://user-images.githubusercontent.com/106368306/170637919-2cbeb19d-13a5-45c0-8deb-0442d9466c57.jpeg)

**Comment by Jaaslet** [comment] 2022-05-27 05:58
Look at the green dungeon, all the way to the right.
Will close this issue, as it's not a bug

**Closed by Jaaslet** 2022-05-27 05:58 UTC
Labels: bug
