### ISSUE TITLE
[SUGGESTION]  Highlight Relevant Areas in Active Quests

### ISSUE THREAD

**Issue by coystream** [pokeclicker/pokeclicker#2107] opened 2022-04-30 19:41 UTC
**Current Behavior**
Currently, there is no indication of which dungeons, towns, and routes are relevant to active quests on the map.

**Improved Behavior**
I think it would be an improvement to highlight dungeons, towns, and routes relevant to active quests.

**Reason for change**
It is very difficult to find specific dungeons when I need them for a quest. Often, I get tired of mouseovering every single location and just google the name and see what route it is near on Bulbapaedia. For dungeons that are entered from a meta-selection inside a city, this would be especially helpful.

**Detailed Description**
 It could be an optional setting and be a customizable color like the already existing highlight options. You take on the quest "Defeat Driftveil Gym in Unova 15 times." and instead of trying to remember which city is Driftveil or clicking on each town until you find the right one, you just take the ship to Unova and click the Pink highlighted city standing out from the rest.

**Comment by Latecomerr** [comment] 2022-05-11 13:23
I would have opened a similar issue for "make it easier for lost players to find required locations", by means of hyperlinking the location name or requiring a doubleclick on the quest name or providing a dropdown of all locations in a region - either of those means would help alleviate the issue

**Comment by RedSparr0w** [comment] 2022-05-12 08:32
Closing as duplicate of #1017

**Closed by RedSparr0w** 2022-05-12 08:32 UTC
