### ISSUE TITLE
eggs and fossils in hatchery queue

### ISSUE THREAD

**Issue by floof123456** [pokeclicker/pokeclicker#3375] opened 2022-11-13 19:57 UTC
### Current Behavior

eggs and fossils are not allowed in the hatchery queue

### Improved Behavior

eggs and fossils being allowed in the hatchery queue

### Reason for change

it makes no sense why fossils and eggs cant be put in the hatchery queue, and its also annoying to have a full hatchery in a place where you have like 96 hatchery slots, but you want to hatch some eggs, its very annoying to have to wait for it to clear itself out.

### Detailed Description

eggs and fossils being allowed to enter the hatchery queue, this way players don't need to wait for a full hatchery queue to empty out.

**Comment by jk13pclick** [comment] 2022-11-13 19:59
Duplicate of #1362

**Closed by jk13pclick** 2022-11-13 19:59 UTC
Labels: suggestion
