### ISSUE TITLE
[BUG] Attack and click attack achievements can revoke itself

### ISSUE THREAD

**Issue by DataCrusade** [pokeclicker/pokeclicker#2659] opened 2022-07-16 22:13 UTC
**Info**
v0.9.7

**Description:**
If you use X-Attack/Click and your attack/click attack hits the threshold for one of the achievements for having a certain amount of either, when it wears off and you reload the game, the achievement will be gone. This can also happen when breeding pokemon takes you below the threshold.

**Steps to Reproduce:**
1. Have an amount of attack that can be boosted or lowered to take you above or below the threshold for an attack achivement
2. Reload the game.
3. The achievement will now be missing and can be reobtained normally

**Expected Behavior:**
Expected is that the achievement will not remove itself once unlocked, and is also the easier solution. 

Another solution would be to make the achievements only grant based on your attack not considering outside factors like items boosting your attack or pokemon in the hatchery lowering your attack by not being hatched yet, but would likely be more difficult to implement.

**Comment by Jaaslet** [comment] 2022-07-19 17:13
Closing as a duplicate of #2351 (yes, i will find a solution some day)

**Closed by Jaaslet** 2022-07-19 17:13 UTC
Labels: bug
