### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Arnyi99** [pokeclicker/pokeclicker#2441] opened 2022-06-13 21:05 UTC
**Info**
 - OS: [e.g. Android]
 - Browser [e.g. Chrome]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment] 2022-06-13 21:07
I can't reproduce this.

**Comment by Arnyi99** [comment] 2022-06-13 21:08
My description is :

Hello on the quest of the mystery of Deoxys, I finished 100 steps of the battle frontier but the quest indicates -2248/100

![Screenshot_20220613-230402](https://user-images.githubusercontent.com/107438804/173445676-e9fc98af-aef0-4a06-9c9e-cbe2886a33dc.png)

**Comment by PixLSteam** [comment] 2022-06-13 21:09
Negative quest progress should be fixed in the next version. You might have to beat 100 more stages though - maybe we should check for this special case to prevent that?

**Comment by Arnyi99** [comment] 2022-06-13 21:13
Ok so I just have to wait for the next update ?

**Comment by jk13pclick** [comment] 2022-06-14 00:49
Closed by #2284

**Closed by jk13pclick** 2022-06-14 00:49 UTC
Labels: bug
