### ISSUE TITLE
[BUG] Pokédex would not show uncaught shiny pokémon

### ISSUE THREAD

**Issue by Saga4755** [pokeclicker/pokeclicker#2201] opened 2022-05-20 11:37 UTC
**Info**
 - OS: Windows 10
 - Browser: Edge
 - Version: 101.0.1210.47

**Description:**
On the pokédex when you check "Uncaught" and "Shiny" options it would not show any pokémon even though I have no shiny pokémon. 

**Steps to Reproduce:**
1. Go to 'Start Menu'. 
2. Go to 'Pokédex'. 
3. Check 'Uncaught' and 'Shiny' options. 
4. See error. 

**Expected Behavior:**
It should show your uncaught shiny pokémon when you check the "Uncaught" and "Shiny" options on the pokédex. 

**Screenshots:**
![Captura de pantalla 2022-05-20 083431](https://user-images.githubusercontent.com/105917739/169520267-5b2ea30c-9cf5-44e1-8fd5-c5b69f3903c7.png)

**Comment by dragonkin550** [comment] 2022-05-20 11:40
you can't have a shiny pokemon in the pokedex without it being caught, uncaught pokemon cannot show in the pokedex as shiny, I see no bug here, other than that you can check those two options at the same time.

**Comment by amative1** [comment] 2022-05-20 13:51
Not a bug. Closing as dragonkin described (shiny is a subset of caught, you can't have uncaught + shiny).

**Closed by amative1** 2022-05-20 13:51 UTC
