### ISSUE TITLE
[Bug]: meltan and melmetal are missing from uncaught pokedex and battle frontier

### ISSUE THREAD

**Issue by milotic** [pokeclicker/pokeclicker#4836] opened 2023-10-08 18:00 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Playing in Galar and dont have meltan or melmetal both still missing from uncaught pokedex, and both never show in battle frontier random mons

![Captura de pantalla 2023-10-08 115027](https://github.com/pokeclicker/pokeclicker/assets/1099848/3324cd79-0132-4b91-9872-60196998964e)

still working in meltan questline but i´m already in galar: 
![Captura de pantalla 2023-10-08 115204](https://github.com/pokeclicker/pokeclicker/assets/1099848/b8e439cb-6864-49f6-8a2f-a08131076fed)

### What did you expect to happen?

Both should appear uncaptured if you don't get before stepping on previous 8th gen content because they are both 7th gen.

### Steps to Reproduce

reach galar
both still missing

### What operating system are you using?

windows 11

### What browsers are you seeing the problem on?

Desktop Client

**Comment by EatPant2nd** [comment] 2023-10-08 18:06
Meltan and Melmetal are optional since they aren't really part of the Alola Dex. They are considered None region and due to this they don't show up in Battle Frontier since said location doesn't show Pokémon from None region.

**Comment by Qwertypop04** [comment] 2023-10-08 18:28
Closing as not a bug

**Closed by Qwertypop04** 2023-10-08 18:28 UTC
Labels: bug
