### ISSUE TITLE
[BUG] The animation that shows when eggs are ready to hatch start just a bit earlier than needed.

### ISSUE THREAD

**Issue by Supacaynan** [pokeclicker/pokeclicker#876] opened 2020-10-06 12:36 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by davmillar** [comment] 2020-10-06 13:37
That is the expected behavior; with 50 steps remaining there will be a slow version of the animation. When fully ready to hatch, a faster version of the animation replaces it.

**Comment by SpenserJ** [comment] 2020-10-06 14:53
@Supacaynan I'm going to close this since it is supposed to start before they're ready to hatch, and we have #875 for adding the ability to disable the animations, but if it is starting the animation earlier than 50 steps, please reopen this issue

**Closed by SpenserJ** 2020-10-06 14:53 UTC
Labels: bug
