### ISSUE TITLE
[BUG] Achievement Modal showing some completed achievements as incomplete

### ISSUE THREAD

**Issue by bvives** [pokeclicker/pokeclicker#2280] opened 2022-05-26 20:30 UTC
**Info**
 - Windows 10
 - Chrome
 - 9.5

**Description:**
4 achiviements that reach 100% completion rate still apears as no completed:

**Steps to Reproduce:**
I don't sure how this happened, i'm pretty sure that when the game updates to 9.4 works fine, but at some point in that version they became incomplete

**Screenshots:**
![image](https://user-images.githubusercontent.com/10503711/170574714-07406c60-873a-412d-992a-99a3504a7cac.png)

**Comment by Ultima1990** [comment] 2022-05-26 20:31
Would be nice if you gave this a proper title.

**Comment by Melvar** [comment] 2022-05-27 14:34
9.5 in Firefox on Linux.
This happened to me with all the farm plot unlock and max oak item level achievements, specifically:
• I sorted by Progress descending, and everything looked normal.
• I selected and completed two of the top few achievements (10k kills on Kanto Route 19 and 12). Unfortunately I didn’t pay attention in between these.
• After reopening the achievement window, the affected achievements were uncompleted.
![grafik](https://user-images.githubusercontent.com/445817/170719917-2d857f04-6f90-4c26-a199-ee1b7231639e.png)
I hope this helps narrow it down.

**Comment by draak491** [comment] 2022-05-30 06:46
v0.9.5 on Windows
The bug seems to be specific to some achievements, I have the same issue and with the exact same achievements.
![Bug](https://user-images.githubusercontent.com/46457606/170932835-9daf9a33-0103-4d03-b432-0f6066fbc943.png)

**Comment by adeuffe** [comment] 2022-05-31 15:18
- V 0.9.5 on Firefox and Windows
- Same achievements.
- As OP I believe it didn't behave like that in V 0.9.4 but can't be sure.
- I counted the complete achievements bonus and it seems to match the displayed number (I get a lower number, I assume because of rounding of displayed values). It looks like the bugged achievements don't give their bonus.
![image](https://user-images.githubusercontent.com/47126185/171206375-772356cb-ee94-4e19-a0ee-fc943705befb.png)

**Comment by Latecomerr** [comment] 2022-06-04 11:39
v0.9.5 on Chrome  
![image](https://user-images.githubusercontent.com/68374728/171997337-967ff3ab-21e9-4cb2-a8ed-971ba2beeddb.png)

**Comment by MokaStitcher** [comment] 2022-06-05 11:20
v 0.95 on Firefox

Can confirm that i've had the same issue, and I found a way to fix and reproduce it on accident.

**How to fix:**

* Change the achievements filters to a setting that doesn't show the oak items and farm plot achievements. for example:
    * `Complete / All / All / Any`
    * `All / any type that is not Oak items and farm / All / Any`
* Optionaly, take note of your achievements bonus %
* Close the game
* Reload the game and your save
* The quests should be marked as complete now, and count towards the achievements bonus


**How to reproduce / break the cheevos again:**

* In the achievement filters, select `Incomplete - All / All / Progress`
* Optionaly, take note of your achievements bonus %
* Close the game
* Reload the game and your save
* The quests for the oak items and farm plots will be at the top of the list, and not counting towards towards the bonus %

This seems to only happen when sorting by progress, not by Default or Bonus %


**How to break only one of the oak items or farm plot cheevos:**

* In the achievement filters, select `All - "Farming" or "Oak Items" / All / Progress`
* Optionaly, take note of your achievements bonus %
* Close the game
* Reload the game and your save
* The quests for the filter you selected will be broken, but not the other.


Hope this helps with solving the issue!

**Closed** 2022-06-24 22:35 UTC
Labels: bug
