### ISSUE TITLE
[BUG] can’t get in game

### ISSUE THREAD

**Issue by blastpika** [pokeclicker/pokeclicker#2409] opened 2022-06-08 21:23 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser  Safari
 - Version .`v0.9.5

**Description:**
Does not let me in game instead it shows a picture of the Kanto Pokémon.

**Steps to Reproduce:**

1. Press the account to get in game.
2. It will show you professer oak giving you a item.
3. It will keep loading.

**Expected Behavior:**

I could not show you a screenshot.

**Additional Information:**
The pokeball keeps loading it should of show the number 299.

**Comment by PixLSteam** [comment] 2022-06-08 21:48
You forgot the OS. Also, a screenshot is basically needed.

**Comment by PixLSteam** [comment] 2022-06-08 22:00
Also, since this issue might be caused by your browser being heavily outdated, please provide its version.

**Comment by NiCeDiCe90** [comment] 2022-06-08 22:09
duplicate of #2371
I think it's just trolling at this point. Please provide information so anyone can actually help you.
Nobody can take this serious since you are the first person to ever report a bug like this but without ANY evidence.

**Comment by blastpika** [comment] 2022-06-08 23:05
I did not change the code.

**Comment by blastpika** [comment] 2022-06-08 23:06
How do I update my browser

**Comment by blastpika** [comment] 2022-06-08 23:10
I tryed it on google it is not working so it is not the browser

**Closed** 2022-06-11 20:48 UTC
Labels: bug
