### ISSUE TITLE
[BUG] Occasionally lose credit for Achievements

### ISSUE THREAD

**Issue by RareKamex** [pokeclicker/pokeclicker#2398] opened 2022-06-07 06:43 UTC
**Info**
 - OS: Windows 11
 - Browser Firefox
 - Version `v0.9.5`

**Description:**
Sometimes, when logging in, the achievements associated with unlocking plots on the farm and those associated with fully upgrading Oak items stay locked, even though I have upgraded all Oak items and unlocked all plots on the farm.  The click attack is considerably lowered when this happens (due to the achievements being considered un-achieved), and I believe it is affecting the coin/dungeon token gain from these achievements as well.

**Steps to Reproduce:**
Unsure; it sometimes is fixed when I log in (meaning all the achievements are reinstated and click power returns to normal), only for it to pop up again on a future login.  Only has happened on the most recent patch; did not happen on patch 0.9.3 and earlier.

**Expected Behavior:**
Achievements stay unlocked when the criteria is met.

**Screenshots:**
![image](https://user-images.githubusercontent.com/106344788/172312727-706695d4-e3d5-409f-9c98-1fbe1a4405cf.png)

**Comment by Jaaslet** [comment] 2022-06-07 07:11
Closing as a duplicate of #2280.
And there is already a fix on the way :)

**Closed by Jaaslet** 2022-06-07 07:11 UTC
Labels: bug
