### ISSUE TITLE
[BUG] Small typo when losing to Lance

### ISSUE THREAD

**Issue by Basic-Person** [pokeclicker/pokeclicker#1577] opened 2021-09-08 13:37 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**
When I lose to Lance I get a message that says "It appears you are not strong enough to defeat Lance2"
I think that the 2 by Lance is a typo

**Steps to Reproduce:**

1. Go to Indigo Plateau Johto 
2. Click on Lance
3. Wait for the timer to go down and lose
4. See typo in losing message

**Expected Behavior:**
Lance would not have a 2 by his name.

**Screenshots:**
<img width="2210" alt="Screenshot 2021-09-08 082841" src="https://user-images.githubusercontent.com/90328949/132518604-77602b6c-ecf5-4f49-8628-40d931787df2.png">

**Additional Information:**

**Comment by Ultima1990** [comment] 2021-09-08 13:42
The 2 is there because we can't have two trainers with the same name and the Kanto version also exists.

**Comment by jk13pclick** [comment] 2021-12-14 19:33
Duplicate of #934 so closing this. Also please see #1599. It seems the fix for this issue is not so simple but there is active interest in solving it.

**Closed by jk13pclick** 2021-12-14 19:33 UTC
Labels: bug
