### ISSUE TITLE
Pokeball loadouts

### ISSUE THREAD

**Issue by BlathersTheOwl** [pokeclicker/pokeclicker#1455] opened 2021-07-16 18:39 UTC
**Current Behavior**
As of now, the pokeballs are interchangeable by category like new pokemon catched pokemon, etc.

**Improved Behavior**
Add pokeball loadouts like with oak items.

**Reason for change**
It makes it a bit more convenient to change pokeball configurations

**Detailed Description**
Just like with oak items, I suggest the addition of pokeball loadouts, so you can quickly switch between certain configurations of pokeballs.

**Comment by Farboo171** [comment] 2023-05-04 15:03
Duplicate of improved sector suggestions, which are now implemented. Closed.

**Closed by Farboo171** 2023-05-04 15:03 UTC
Labels: approved
