### ISSUE TITLE
[SUGGESTION] There should be an Auto-dungeon feature, similar to the auto-gym feature

### ISSUE THREAD

**Issue by Keysblade** [pokeclicker/pokeclicker#1630] opened 2021-11-01 20:43 UTC
**Current Behavior**
You have to manually go through the dungeons

**Improved Behavior**
Have an auto-start feature on dungeons,

**Reason for change**
Going through dungeons are time consuming, especially with later regions

**Detailed Description**
Similarly to how there's a button that allows you to refight a Gym for a price, there can be a button that allows you to fight the dungeon's boss/bosses for an increased amount of dungeon tokens
**Screenshots:**

**Comment by jk13pclick** [comment] 2021-11-01 20:51
Duplicate issue of #1315 , probably won't work with any Dungeon Rework plans.

**Comment by RedSparr0w** [comment] 2021-11-01 21:56
Closing as duplicate of #1315.

Please post any relevant info in there if there's anything missing you would like to add.

**Closed by RedSparr0w** 2021-11-01 21:56 UTC
