### ISSUE TITLE
Adding fossils and eggs to the hatching queue

### ISSUE THREAD

**Issue by Samantha7734** [pokeclicker/pokeclicker#1868] opened 2022-03-14 11:05 UTC
**Current Behavior**
 we must wait until our eggs slots are empty in order to add eggs or fossils

**Improved Behavior**
 the ability to queue up eggs and fossils alongside the hatchery queue

**Reason for change**
 convenience mostly just annoying having to wait and not queue things up

**Detailed Description**
 currently we must wait and stop adding things to the hatchery queue in order to hatch eggs and fossils. if we could add them to the queue that'd be less waiting around in less tedium.

**Screenshots:**

**Comment by amative1** [comment] 2022-03-14 11:09
Closing as duplicate of #1362

**Closed by amative1** 2022-03-14 11:09 UTC
