### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by Death2519** [pokeclicker/pokeclicker#2051] opened 2022-04-21 01:49 UTC
Pokeball settings
**Current Behavior**

Lets you set up pokeballs for already caught, already caught shiny, new, new shiny
**Improved Behavior**

some way to set a pokeball to like only caught pokemon 50% or below or legendries only
**Reason for change**

It would help with not using/wasting types of pokeballs
**Detailed Description**

Like on the bottom of the already developed pokeball settings there would be an option like one way it could be developed is you click on the left and select your pokeball then use a scroll bar to select what percentage then on the right what it would replace, like one of the already made catagories.
**Screenshots:**

**Comment by amative1** [comment] 2022-04-21 02:17
Not sure what you mean by "caught Pokémon 50% or below". Pokémon are either caught or they aren't.

**Comment by Death2519** [comment] 2022-04-21 02:26
> Not sure what you mean by "caught Pokémon 50% or below". Pokémon are either caught or they aren't.

What i was trying to say there was about the pokemon catch rates, like if you have a pokemon with 67% catch rate or one with 43%

**Comment by RedSparr0w** [comment] 2022-04-23 22:58
closing as duplicate of #2046 

(if not everything is covered by that issue, feel free to leave a comment there)

**Closed by RedSparr0w** 2022-04-23 22:58 UTC
