### ISSUE TITLE
[SUGGESTION] Add ability to organise achievements by %

### ISSUE THREAD

**Issue by miniblitz** [pokeclicker/pokeclicker#2132] opened 2022-05-08 15:05 UTC
I would appreciate the ability to organise achievements by the % of achievement bonus.

**Current Behavior**
Right now the game only has the ability to filter achievements but not sort them.

**Improved Behavior**
The ability to sort achievements, particularly by achievement bonus %.

**Reason for change**
I'm in the endgame, and trying to complete achievements for each region one by one. I realised it takes less time to get the 0.22% bonus of Alola for 100 route kills versus the 0.71% bonus for 10000 route kills in Hoenn. By being able to sort and get all the easier achievements done, I think it will allow for more efficient ability to complete achievements (especially given the bonus to click attack and flute effects).

**Detailed Description**
Just adding one of those arrows that is present in the hatchery or Pokemon List allowing the list to go front-to-back or back-to-front. In this scenario it would be ordering based on the % bonus.

**Comment by CorgiOnNeptune** [comment] 2022-05-08 16:01
Suggestion already approved in #2040.

**Comment by Jaaslet** [comment] 2022-05-25 09:06
I will close this as a duplicate of #2040

**Closed by Jaaslet** 2022-05-25 09:06 UTC
