### ISSUE TITLE
[Suggestion] Alternate Regions as Prestige Rewards

### ISSUE THREAD

**Issue by danfroese** [pokeclicker/pokeclicker#663] opened 2020-04-17 08:24 UTC
I suggest that the player starts in a region, runs through that region, and after a certain end goal has been met (beat elite 4, finish final dungeon, complete the pokedex, etc.) then they can choose to retire and start again (losing all pokemon and upgrades) with some kind of bonus, like the skillpoint system that I understand is being planned. If the player completes certain special challenges, they unlock additional options, including the eventual unlocking of the next region. When starting a new run, the player can select from any region they have unlocked.

If the player only ever plays a single region in one play, then you don't have to worry about suppressing damage of out-of-region pokemon, or about the list of the player's pokemon becoming too long. New regions can be designed without needing to worry about what's available in other regions, and can be more self-contained.

**Comment by anapple96** [comment] 2020-04-17 08:26
this is basically a duplicate of a few issues.

**Comment by danfroese** [comment] 2020-04-17 14:09
It's a bit of an amalgamation of ideas. The key point though is having the regions be distinct and separate, expecting that the player will not move freely between regions without doing a soft reset. I didn't see anything about this one way or another in the other topics.

**Comment by anapple96** [comment] 2020-10-17 10:40
Well, we can safely close this now, as I can't see a single use for it

**Comment by anapple96** [comment] 2020-10-17 10:40
And, the plan is not to have a full prestige anyway, so locking regions behind this is sorta weird

**Closed** 2020-10-17 11:29 UTC
