### ISSUE TITLE
[BUG] Quests not claimable.

### ISSUE THREAD

**Issue by im00boss** [pokeclicker/pokeclicker#1065] opened 2020-11-13 17:10 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version `v0.6.3`

**Description:**

**Steps to Reproduce:**

1. Complete any quest, to me personally it happened on a "catch a shiny" quest and a "defeat x amount of pokemon on Route x" 

**Expected Behavior:**

**Screenshots:**

[Pokéclicker 2.pdf](https://github.com/pokeclicker/pokeclicker/files/5538272/Pokeclicker.2.pdf)

**Additional Information:**
Screenshot is a recreation and attempted recreation of the 2 quests. The second was a failure as I could not find a shiny. 

 -->

**Comment by Ultima1990** [comment] 2020-11-13 17:36
Duplicate of #1064 

Please check if an issue for your bug or issue has already been created.

**Closed** 2020-11-14 22:35 UTC
Labels: bug
