### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Osow96** [pokeclicker/pokeclicker#2454] opened 2022-06-14 20:34 UTC
**Info**
 - OS: Windows 10
 - Browser: Opera
 - Version: 87.0.4390.45

**Description:**
achivements remains incomplete at 100%

**Steps to Reproduce:**
1. Go to Achivements tracker
2. Click on 'List'
3. Click on Status box -> Incomplete
4. See five achiments at 100% 

**Expected Behavior:**
I expected that this achivements percentage has added to my achivement bonus

**Screenshots:**
![image](https://user-images.githubusercontent.com/107511271/173683554-4b5157cb-4ce6-43de-844c-2741c4ed5ff9.png)

**Additional Information:**

**Comment by Jaaslet** [comment] 2022-06-14 20:36
Closing as a duplicate of #2280

**Closed by Jaaslet** 2022-06-14 20:36 UTC
Labels: bug
