### ISSUE TITLE
[BUG] Ultra beast hunt mission bug

### ISSUE THREAD

**Issue by Sophiebyd** [pokeclicker/pokeclicker#2856] opened 2022-08-14 11:59 UTC
**Info**
 - OS: Windows 10
 - Browser : Firefox
 - Version 103.0.2

**Description:**
I got my mission achieved (catch Buzzwole and Pheromosa), but the mission is stuck in quest section and i can't access to the next mission. And even if i talk to Anabel for getting the next one, she still talking about the actual mission which is completed.

**Steps to Reproduce:**

**Expected Behavior:**
pass to the next mission 

**Screenshots:**
https://puu.sh/Jg8Mb/780bcaa556.png
https://puu.sh/Jg8Mp/893af5cfe6.png

**Additional Information:**

**Comment by PixLSteam** [comment] 2022-08-14 12:20
Duplicate of #2804

**Closed by PixLSteam** 2022-08-14 12:20 UTC
Labels: bug
