### ISSUE TITLE
[BUG] i cant use token colletor

### ISSUE THREAD

**Issue by Nitonoa** [pokeclicker/pokeclicker#2580] opened 2022-07-04 14:10 UTC
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment] 2022-07-04 14:12
Please fill out the template properly when reporting bugs.
Duplicate of https://github.com/pokeclicker/pokeclicker/issues/2551 https://github.com/pokeclicker/pokeclicker/issues/2522 https://github.com/pokeclicker/pokeclicker/issues/2520 https://github.com/pokeclicker/pokeclicker/issues/2558 https://github.com/pokeclicker/pokeclicker/issues/2561
Should be fixed with https://github.com/pokeclicker/pokeclicker/pull/2543

**Closed by PixLSteam** 2022-07-04 14:12 UTC
Labels: bug
