### ISSUE TITLE
[SUGGESTION] Add notification settings for Underground

### ISSUE THREAD

**Issue by TheSpace3100** [pokeclicker/pokeclicker#2323] opened 2022-05-29 17:31 UTC
**Current Behavior**
We can currently only edit notification settings for general, farm and hatchery

**Improved Behavior**
I think it would be better if we can also edit notification for underground.

**Reason for change**
I use notification to catch my attention when something important is going on but I'm always disapointed by Undergroud notif. 

**Detailed Description**
It would be cool if at less 2 more settings appeard such as : "find an item in Underground" and "dig deeper in undergound"

Thank you for your attention and sorry for my bad english (I'm french btw)

**Comment by PixLSteam** [comment] 2022-05-29 17:40
Duplicate of #2180

**Closed** 2022-05-29 17:43 UTC
