### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shadowmarsh13** [pokeclicker/pokeclicker#2811] opened 2022-08-04 16:35 UTC
Windows 10
 - Browser: Edge
 - Version: v0.9.10

**Description:**
Caught Kartana 4 times and Celesteela 2 times and the bars are full for the quests but it isn't completing the part of the quest and I've talked to all of the npcs in the hotel and they are all saying the same thing from before. I've tried refreshing the page, downloading and importing the save, and recatching the mons the specified amount of times 
**Steps to Reproduce:**
1. talk to nanu
2. kahuna nanu tells you about the new ubs and I caught them in the Malie Garden
3. the bars are full but I cannot progress to the next step of hte quest

**Expected Behavior:**
I would catch the ubs and be able to battle nanu and then be able to move on to catching blacephalon and guzzlord
**Screenshots:**

![Screenshot (1)](https://user-images.githubusercontent.com/110623679/182903880-47452042-cca9-4762-b5fe-6b18cfa8e9e6.png)

**Additional Information:**

**Comment by lenormandSeb** [comment] 2022-08-04 17:28
Did you disable script before retry ?

**Comment by shadowmarsh13** [comment] 2022-08-04 17:30
I just tried that but it didn't work

**Comment by Qwertypop04** [comment] 2022-08-05 09:25
Closing as duplicate of #2804

**Closed by Qwertypop04** 2022-08-05 09:25 UTC
Labels: bug
