### ISSUE TITLE
[BUG] Already vomplete achievements came back but are still red 

### ISSUE THREAD

**Issue by Zegoutte** [pokeclicker/pokeclicker#2349] opened 2022-06-01 12:32 UTC
**Info**
 - OS: Windows 10
 - Browser : Opera
 - Version : 87.0.4390.36

**Description:**
I found that already completed achievement are back but are still red.

**Steps to Reproduce:**

1. Go to 'Achievement Tracker'
2. See error

**Expected Behavior:**
Those achievement must be green.

**Screenshots:**
![image_2022-06-01_143224591](https://user-images.githubusercontent.com/106674567/171405141-fd2b5851-58d2-431f-bced-80e92cb58cbb.png)

**Comment by S0rab** [comment] 2022-06-02 13:51
i have the same bug and is there a solution yet 
![Capture d’écran 2022-06-02 155111](https://user-images.githubusercontent.com/106754469/171644783-2fd4ff5d-db97-4699-aae2-043e89aa4cc9.png)
?

**Comment by amative1** [comment] 2022-06-04 01:13
Duplicate of #2280

**Closed by amative1** 2022-06-04 01:13 UTC
Labels: bug
