### ISSUE TITLE
[Bug]: Primal Reversion step "Find one Mystic Water" uncompletes if Mystic Water is given to a Pokemon

### ISSUE THREAD

**Issue by IdsHendriks** [pokeclicker/pokeclicker#4832] opened 2023-10-07 19:20 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

I ran the dungeon Sea Spirit's Den to obtain a Mystic Water for the Primal Reversion quest. After obtaining it, the portion of the quest labeled "Find one Mystic Water" was completed. I then proceeded to give this Mystic Water to one of my Pokemon. After this, the "Find one Mystic Water" portion of the quest was no longer completed.

### What did you expect to happen?

I expected this portion of the quest to remain completed. (Using a Metal Coat, by contrast, did not decrement the amount found.)

### Steps to Reproduce

1. Proceed through the Primal Reversion quest, until the point where you gather items for Captain Stern.
2. Obtain a Mystic Water
3. The step "Find one Mystic Water" is now completed
4. Give the Mystic Water to a Pokemon
5. The step "Find one Mystic Water" is no longer completed

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Chrome

### Additional Information

UPDATE: Opening the game the next day, the "Find one Mystic Water" step is back to being completed, so maybe this is only a display issue.

**Comment by DorkyDelphox** [comment] 2023-10-07 19:48
your mystic water total went down by one so the game picked up on that as you losing one in the quest too, it tracks your current amount and changes based on it going up or down. think the only thing you can do is go get another and dont use it until you complete that quest step

**Comment by IdsHendriks** [comment] 2023-10-07 19:51
1. The quest states you have to _find_ a Mystic Water, not have one
2. As stated in the report, I tried this with a Metal Coat as well, and the quest progress for that did not decrement.

**Comment by Qwertypop04** [comment] 2023-10-07 20:13
1. As far as the game is concerned, you found one then unfound one. Not how it should work, but how it currently does.

2. Metal Coat is an evolution item. Completely different.

**Comment by RegisCoaxans** [comment] 2023-10-11 21:41
There should be no difference between quest counts behave for Metal Coat and Mystic Water, since they are both tracked on item counts.
The cause of this is probably as described in #4809.

**Comment by RegisCoaxans** [comment] 2023-11-04 18:10
Closed by https://github.com/pokeclicker/pokeclicker/pull/4809 !

**Closed** 2023-11-05 01:12 UTC
Labels: bug
