### ISSUE TITLE
[Using C++ server to save player's data] 

### ISSUE THREAD

**Issue by nmarrocchi** [pokeclicker/pokeclicker#2276] opened 2022-05-26 11:49 UTC
In order to set up an online backup allowing to play across different browsers and devices, you could use a C++ server using websocket to transmit the player's data to a database, this would allow all players to play across different devices without having to transfer the backup file each time
![Load Save Pokeclicker](https://user-images.githubusercontent.com/70692887/170482256-58e02544-459c-4cca-8a5f-036bf79331fe.png)
![Save Pokeclicker](https://user-images.githubusercontent.com/70692887/170482260-f455b5eb-f2a2-4fd1-9bd4-693f156c7243.png)

**Comment by Jaaslet** [comment] 2022-05-26 13:24
Will close as a duplicate of  #340.
Personally i don't think it will happen because servers are expensive and the game is getting quite popular

**Closed by Jaaslet** 2022-05-26 13:24 UTC
