### ISSUE TITLE
[BUG] One pokemon has disappeared

### ISSUE THREAD

**Issue by DeswingBE** [pokeclicker/pokeclicker#2770] opened 2022-07-27 21:53 UTC
**Info**
 - OS: Windows 10
 - Browser Firefox
 - Version v0.9.9

**Description:**
One pokemon has disappeared from my pokemon list , and I cannot breed it anymore as well (it's Butterfree) , I can see it in my pokedex though

**Steps to Reproduce:**
No reproductible method, just spotted him missing today

**Expected Behavior:**
Pokemon still present :) 

**Screenshots:**
![image](https://user-images.githubusercontent.com/44812822/181379133-1ed2ae33-d49d-4be7-b931-cd4bca10260a.png)

**Comment by StyvSkells** [comment] 2022-07-30 10:40
Same problem
4 pokemons disapeared : ex
Gengar
Armoured Mewtwo
...

**Comment by Dagon-Attano** [comment] 2022-07-31 09:22
Same problem 
Only two noticed:
Flabebe Yellow
Flabebe White

**Comment by flavien-Ch** [comment] 2022-08-01 07:54
Hello, same problem since at least ten days.
sevral pokemon disappeared.

A kind of solution have been found?
the next patch will fix it?

thanks for the good news :)

**Comment by Charivarii** [comment] 2022-08-01 10:36
Hello ! 
I have the same problem since one or two days after the last update (22/07/2022).
Pokemon have disappeared including Gyarados and Manaphy, my two highest attack pokemon, and I can't breed them anymore :/
Thanks for your consideration.

**Comment by NiCeDiCe90** [comment] 2022-08-01 10:39
Do any of you have a save file from before the update (where the Pokemon are still there) + a current savefile?
We still didn't manage to reproduce the Bug a single time. Maybe we find at least 1 file where we can actually see them disappearing while updating or something like this.

**Comment by Charivarii** [comment] 2022-08-01 10:59
[[v0.9.7] PokeClickerSave_2022-07-22 10 06 29.txt](https://github.com/pokeclicker/pokeclicker/files/9233251/v0.9.7.PokeClickerSave_2022-07-22.10.06.29.txt)

Here is my save before the update, with at least Gyarados, Manaphy, Toxycroak, Clefeable and Phione.

[[v0.9.9] PokeClickerSave_2022-08-01 10 56 49.txt](https://github.com/pokeclicker/pokeclicker/files/9233284/v0.9.9.PokeClickerSave_2022-08-01.10.56.49.txt)

And the second one is today, where I don't have this pokemon anymore.

**Comment by NiCeDiCe90** [comment] 2022-08-01 11:02
I just updated your 0.9.7 save and all the mentioned Pokémon were still there. So the update itself can't be the problem.
Are you sure you didn't run any scripts or plugins for the game while updating?

**Comment by Charivarii** [comment] 2022-08-01 11:13
They disappered one or two days after the update, I didn't know when exactly and why.
I play without any script or plugin, just I went to work with my pc on with breed Helpers, and when I came back, they were gone and I think they disappered not at the same time.

**Comment by lenormandSeb** [comment] 2022-08-01 11:17
Which helper ? Please

**Comment by Charivarii** [comment] 2022-08-01 11:20
Sam, Blake and Parker. I often use this 3 helpers at the same time.
![Helpers](https://user-images.githubusercontent.com/22845812/182137236-92309768-1dd4-4d31-84a6-99ab859f3045.PNG)

**Comment by Stardust600** [comment] 2022-08-01 19:54
Hello I have the same issue.
During breeding,  4 pokemons disappered: Serperior hydreigon krokodile Unzefant 
Do you find any solution?
Helper used : Noël carey justice
thanks

**Comment by lenormandSeb** [comment] 2022-08-01 21:20
No, still no solution.
No script use ?

**Comment by Stardust600** [comment] 2022-08-01 21:54
nope

**Comment by Stardust600** [comment] 2022-08-01 22:03
If I May add something : I noticed sometimes in the Hatchery list, some egg disappered, but the eggs on the queue cannot take " the vacant place", you must choose a pokemon to fill this place and then the breeding can continue normally

**Comment by NashNash7** [comment] 2022-08-02 11:42
pokemons disappered  for me : magikarp, gyarados, croagunk, toxicroak, Manaphy, Phione, Clauncher, Furfrou, Cleffa, Igglybuff, Clawitzer, Clefairy, Azurill, Musharna, Pichu, Munna, Pikachu, Gogoat, Skiddo, Spritzee, Litleo, Espurr

There may be more. I guess the bug come from hatchery. (May be when you fire a helper).

**Comment by flavien-Ch** [comment] 2022-08-02 20:55
> If I May add something : I noticed sometimes in the Hatchery list, some egg disappered, but the eggs on the queue cannot take " the vacant place", you must choose a pokemon to fill this place and then the breeding can continue normally

J'ai la même réflexion que toi sur ce sujet. J'utilise différent helper aussi.

I have the same thinking as you are. I use different helpers too.

**Comment by Stardust600** [comment] 2022-08-02 21:11
oui, j'ai remarqué que ce problème venait aussi après un rafraîchissement de page  je ne sais pas si c'est lié

**Comment by Ultima1990** [comment] 2022-08-02 21:12
> oui, j'ai remarqué que ce problème venait aussi après un rafraîchissement de page je ne sais pas si c'est lié

We don't speak French around here.

**Comment by Stardust600** [comment] 2022-08-02 21:14
sorry just little time to make a correct sentence

**Comment by Kyuryia** [comment] 2022-08-02 23:51
It happened for me too when I logged in after the update. My hatchery was empty while the queue was full and I lost 4 Pokémon: Tornadus and Landorus for sure, I haven't spot the 2 others yet
I don't use scripts nor Helpers

**Comment by Kyuryia** [comment] 2022-08-02 23:56
It happened for me too when I logged in after the update. My hatchery was empty while the queue was full and I lost 4 Pokémon: Tornadus, Landorus, Armored Mewtwo and Aerodactyl
I don't use scripts nor Helpers

**Comment by flavien-Ch** [comment] 2022-08-03 06:03
> > oui, j'ai remarqué que ce problème venait aussi après un rafraîchissement de page je ne sais pas si c'est lié
> 
> We don't speak French around here.

Yes, instead, we translate the sentence, don't worried about that ;)

**Comment by Stardust600** [comment] 2022-08-03 07:21
yes me too!
Thanks !!

**Comment by Jaaslet** [comment] 2022-08-03 08:02
We have done some stuff, that might fix it. And if that does not work, we have added some code, which fixes it on reload.
If it still happens, we need some more information on how to consistently reproduce it. So i will close this issue

**Closed by Jaaslet** 2022-08-03 08:02 UTC
Labels: bug
