### ISSUE TITLE
[SUGGESTION] Friendship Makes Everyone Shine! (Use for Rare Candies, and Luxury Balls)

### ISSUE THREAD

**Issue by GarrikFel** [pokeclicker/pokeclicker#1541] opened 2021-08-27 15:08 UTC
**Current Behavior**

Right now, rare candies and luxury balls do nothing

**Improved Behavior**

Add a "Friendship" mechanic, where rare candies and luxury balls increase it.  Friendship would very slightly increase the odds of hatching a shiny

**Reason for change**

It gives rare candies and luxury balls a use.

**Detailed Description**

I had posted this in the discord as kind of a joke, but the more I thought about it, the more reasonable it seems.  The goal is to implement rare candies into the game.  

In the main series, rare candies increase level, and friendship, so let's make a friendship mechanic.  Add a new stat to pokemon (friendship: number), which slightly increases the odds to hatch a shiny.  The intention is to make it a little easier to get those couple of shines that you REALLY want.  Make rare candies very expensive (more than proteins, less than masterballs) so that it acts like a money sink, so that you can't do this for all pokemon.  

Say, if the normal egg hatching rate is 1/1024, then 1 point of friendship increases the rate to 1/1023.  Maybe set a max of 100 friendship per pokemon so that you can't guarantee the shiny to hatch every egg.  I personally like the cap to be 202, so that way if you have a full farm and shiny charm, it increases the odds of a shiny to 1/151 (353-202=151).  Another option would be to add a multiplier (1 + .01*friendship), which would add a nice diminishing returns curve, so that you don't really need a cap (thank you Penguin for suggesting this idea).

Luxury balls would essentially do the same thing.  They'd be cheaper than rare candies, but the downside is that you'll probably waste most of them on pokemon you don't care about since you have to use them on routes and dungeons.  But this would give newer players something to work with until they could afford rare candies, and it would incentivize farming.

This is a new mechanic, so it needs to be discussed, and experimented with before it can be implemented.  If people don't like it, it's cool, but I think it's a neat idea that makes rare candies and luxury balls useful while staying on brand, and helps with the late game money issue, and makes farming a little more fun once you've unlocked everything.

**Comment by GarrikFel** [comment] 2021-08-28 13:35
The problem with rare candies is that this game doesn't have a mechanic that it can really help with.  Getting levels is already easy, proteins exist, and unless we want to set up a system where rare candies increase the max level (which I wouldn't recommend), there's nothing for rare candies to work with... unless you work with their "increases friendship" property.  

To be fair, it would still have a use after you get the shiny pokemon.  It would help speed up the "Catch 1 Shiny" quest.

Personally, I don't have too high of an opinion of rare candies.  They level up your pokemon without EVs or stat experience, and so the level ups it provides aren't the best.  I don't value them the same way you do.

The goal here is to find a use for rare candies (and luxury balls too I suppose).  Let's brainstorm and come up with something.  What does everyone feel rare candies should do in this game?  Let's discuss, and find something we all like, and implement it by the end of the year!

**Comment by NiCeDiCe90** [comment] 2021-08-28 16:21
I made a suggestion about rare candys a few month ago: #1407
In my opinion that would fit the theme of the rare candy better.

**Comment by GarrikFel** [comment] 2021-08-28 19:52
I like your suggestion, but it needs to be balanced differently.  I responded to your suggestion with my suggestion about balancing in #1407.  Ok, what else do we have for suggestions?

**Comment by Farboo171** [comment] 2023-05-04 15:30
Since Luxury Balls have a use now, closing as duplicate of #1407

**Closed by Farboo171** 2023-05-04 15:30 UTC

**Comment by refinedlivingstyle** [comment] 2025-10-20 00:47
Turning rare candies and luxury balls into friendship boosters is such a clever way to add depth. It gives players more strategy, more incentive to farm, and a meaningful path to those dream shinies.
