### ISSUE TITLE
[Bug]: bug

### ISSUE THREAD

**Issue by zndqs** [pokeclicker/pokeclicker#3466] opened 2022-11-24 17:02 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

![image](https://user-images.githubusercontent.com/99935313/203836003-bec085b4-8fc9-4f8f-85df-91dad8fd7d25.png)
i sold 5 spooky plate then my task require 6 spooky plate

### What did you expect to happen?

dont require 6 spooky plate

### Steps to Reproduce

1 start zero`s ambition  task
2 sell sold 5 spooky plate
3 boom

### What browsers are you seeing the problem on?

Chrome

**Comment by Razikd29** [comment] 2022-11-24 17:04
Known, try refreshing your game and/or gaining 6 Spooky Plates

**Comment by PixLSteam** [comment] 2022-11-24 17:05
Duplicate of #3123

**Closed by PixLSteam** 2022-11-24 17:05 UTC
Labels: bug
