### ISSUE TITLE
[SUGGESTION]: Weather channel 

### ISSUE THREAD

**Issue by Narobii** [pokeclicker/pokeclicker#4042] opened 2023-03-24 21:27 UTC
### Current Behavior

currently to see the weather in other regions you have to travel to every region and see what the weather is. All this boat travel can't be great for the pokeworld and also is slow and inconvenient.

### Improved Behavior

A weather channel in the fashion of Poke ball, Town Map, and shortcuts that will show each region and the ongoing weather that is currently unlocked. Kanto: sunny Johto: rainy etc etc.

### Reason for change

This makes traveling for certain weather dependent events easier, including hoenn castforms and kalos goomy line requiring rain.

### Detailed Description

A new module, either optional in settings or not, that displays a the region name or other region identifier with the current weather name or identifier symbol.

**Comment by RegisCoaxans** [comment] 2023-03-24 21:34
Somehow a duplicate of #4006.

**Comment by osherwott** [comment] 2023-04-11 22:09
Closing. Duplicate of #4006.

**Closed by osherwott** 2023-04-11 22:09 UTC
Labels: suggestion
