### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Redmtr5** [pokeclicker/pokeclicker#4343] opened 2023-05-21 04:18 UTC
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

When trying to reach 100k Defeated Pokemon in the Pikan Forest when i noticed a white icon depicting the Pokemon's gender. It happens every so often, not continuously. Mainly shown up the both genders of Nidoran.

### What did you expect to happen?

For the Pokemon to display its gender correctly, blue for male and pink for female

### Steps to Reproduce

1. Go to the Sevi Islands (4,5,6,7) and Route 3 in Kanto
2. Click on corresponding Route
3. Wait for Nidoran to appear

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
none
```

### Additional Information

![image](https://github.com/pokeclicker/pokeclicker/assets/134184466/70a35441-61f2-4bcc-8967-a52570843c3e)
![image](https://github.com/pokeclicker/pokeclicker/assets/134184466/f43bd468-2e8a-4829-845a-d21fffa3d9f9)

**Comment by osherwott** [comment] 2023-05-21 04:21
Not a bug, a feature!
#4189 
Closing

**Closed by osherwott** 2023-05-21 04:21 UTC
Labels: bug
