### ISSUE TITLE
[BUG] MissingNo. is the Save File Pokemon before a starter is picked.

### ISSUE THREAD

**Issue by jameswasson** [pokeclicker/pokeclicker#1763] opened 2022-01-09 04:05 UTC
**Info**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.8.13

**Description:**
if the starter Pokémon had not been caught when the game saves for the first time for a new player, the Pokémon displayed on the save file is MissingNo.

**Steps to Reproduce:**
1. Start a new save.
1. Do not pick any starter. Wait for the game to save (no more than 10 seconds).
1. Refresh the game
1. Note the Pokémon on the save file is MissingNo.

**Expected Behavior:**
No Pokémon should be on the save file if no Pokémon have been caught.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7018593/148668938-fc9a3745-3564-4943-bbf1-0f7e3ed72877.png)

**Additional Information:**
MissingNo. is a special Pokémon for weird glitch-like situations, and may be a good Pokémon to show on something like a corrupted save. In this case though the save file is not in a glitched state so there shouldn't be a glitch Pokémon on it.

**Comment by Qwertypop4** [comment] 2022-01-09 04:12
Intentional Easter Egg

**Comment by amative1** [comment] 2022-01-09 04:17
Closing as intended behavior.

**Closed by amative1** 2022-01-09 04:17 UTC
Labels: bug
