### ISSUE TITLE
[SUGGESTION] Putting eggs & fossiles into hatching queue

### ISSUE THREAD

**Issue by josariexp** [pokeclicker/pokeclicker#2449] opened 2022-06-14 17:06 UTC
**Current Behavior**

Right now, you can choose 4 pokemons to put in hatching queue so when a pokemon egg finally opens, automatically generate another egg from the first pokemon in hatching queue, but you are only capable of choosing pokemons, not eggs or fossiles. If you want to start hatching an egg or fossile, you have to delete the queue, wait until there is an empty slot in the hatchery, and chose the egg or fossil.

**Improved Behavior**

Once you open the hatchery list, you can click on am egg or a fossile and it will be added to the queue.

**Reason for change**

If we can choose eggs or fossiles to put in the hatching queue, it would be a lot easier to hatch thoses eggs or fossiles without the need to delete all the queue in order to have the possibility to start hatching an egg or a fossil.
**Detailed Description**

Adding to eggs from shops and fossiles from underground, the capability to be in the hatchery queue

**Screenshots:**

**Comment by Jaaslet** [comment] 2022-06-14 17:07
Closing as a duplicate of #1362 (and there is already an open PR, that solves this)

**Closed by Jaaslet** 2022-06-14 17:07 UTC
