### ISSUE TITLE
[SUGGESTION]: New Challenge Mode: 50 EV Hard Cap

### ISSUE THREAD

**Issue by alt1noreply** [pokeclicker/pokeclicker#4277] opened 2023-05-09 14:12 UTC
### Current Behavior

When a Pokemon is infected by Pokerus, it may gain Effort Values (EVs) that multiply the attack of that Pokemon. If a Pokemon has less than 50 EVs (Pokerus Status: Contagious), the EV multiplier increases by 0.01 per EV, which means a Pokemon gains 1% extra damage per EV for the first 50 EVs.

Beyond 50 EVs (Pokerus Status: Resistant), a Pokemon may still gain EVs, albeit with diminishing returns to the EV Damage Multiplier Bonus. There is no limit to the multiplier or the total amount of EVs a Pokemon can obtain.

### Improved Behavior

Once a Pokemon has obtained 50 EVs and Pokerus Status has shifted from Contagious to Resistant, that Pokemon will no longer be able to obtain EVs. This will cap the EV Damage Multiplier bonus to 1.5x

### Reason for change

With EVs technically being infinite, Pokemon can reach absurd Damage numbers rather quickly. Adding an optional Challenge Mode that stops EV gain once a Pokemon's Pokerus status is Resistant would definitely increase the game's overall difficulty since Pokemon won't be able to scale infinitely. On top of that, it simplifies EV training, as once a Pokemon is Resistant, they are simply done; No more constant grinding necessary.

### Detailed Description

I understand there is a Challenge Mode already that slows EV gain by 10x, but that one still allows for infinite EV gains. This would be different, as Pokemon would gain EVs like normal until 50, then simply be done. Would make EV training more like a check-box thing for completion and you don't have to stress about a Pokemon's damage numbers skyrocketing and making the game too easy.

**Comment by LuchoDreamer** [comment] 2023-05-09 14:16
EVs are infinite, but after 50 they grow logarithmically, so no, they grow very slowly, even more with slow EV challenge.
Believe me, numbers don't just skyrocket as easy as you think. This is not necessary.

**Comment by Qwertypop04** [comment] 2023-05-09 14:20
As Lucho says, this is completely unnecessary, the Slow EVs challenge already exists. Even without it, it takes a lot of effort to go much further than 1.5x.

**Comment by PixLSteam** [comment] 2023-05-09 14:21
Closing because this is more or less a duplicate of the closed suggestion #3107.

**Comment by alt1noreply** [comment] 2023-05-09 14:21
My main issue with them is that they are out of the player's direct control. Once a Pokemon is infected with Pokerus, it will always and forever gain EVs, effecting that Pokemon's Damage without the player's intervention.

**Closed by PixLSteam** 2023-05-09 14:21 UTC
Labels: suggestion

**Comment by alt1noreply** [comment] 2023-05-09 14:36
I have trouble articulating why I feel so uncomfortable with it. 

I do not like it when the Pokemon's damage numbers go up without my consent. Laugh at me all you want, but its my OCD. I like to have certain Pokemon be near each other in damage numbers, like I had all the starters in a close range, fossil Pokemon, box legendaries, etc. When these numbers start going up on their own, I lose that control over the numbers and my mind just cannot handle that. 

And I have tried Pokerus stuff before. Made a backup save, started spreading it around to get achievements, and really wasn't a fan of the process. One of the Pokemon was Magikarp, and not too long after I started it the update with Magikarp Island came out and my heart sank. Watching a Magikarp's damage numbers shoot up way past the others made me feel ill, so I immediately reverted back to the save file from before spreading Pokerus. And I really lost a lot of motivation to play the game. 

And this wasn't really a big issue since I could easily ignore it, but then they added Achievements related to Pokerus. Now it is impossible to 100% the game without spreading Pokerus. Which means there will always be Click Damage bonuses I will never be able to obtain. 

I just do not want damage numbers doing up infinitely without anything I can do to stop it.

**Comment by PixLSteam** [comment] 2023-05-09 14:40
> without anything I can do to stop it.
Lucho told you how to stop it.
Regardless, challenge modes to disable or severely limit a feature will not be implemented simply because a single person does not like the feature.

**Comment by alt1noreply** [comment] 2023-05-09 14:43
"Lucho told you how to stop it."
Setting the filter to not catch Resistant Pokemon prevents idling on routes to gain Dungeon Tokens efficiently.

**Comment by Qwertypop04** [comment] 2023-05-09 14:46
> "Lucho told you how to stop it."
> Setting the filter to not catch Resistant Pokemon prevents idling on routes to gain Dungeon Tokens efficiently.

Yes, but you *can* stop it. Since we aren't planning on adding this, I'm afraid that's your only option if you don't want to gain more. I understand that this is irritating for you, but it simply isn't worth adding an extra challenge for such a small audience

**Comment by alt1noreply** [comment] 2023-05-09 14:52
I may give it a try out of good faith, but technically there will come a point where it will be impossible to acquire Dungeon Tokens once all Pokemon are able to be made Resistant.

**Comment by Aegyo** [comment] 2023-05-09 16:18
I don't think this is going to be implemented, you would have more luck with a custom script to limit EV gains
